(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"ciclo andar boton sonido version clase sin camara prueba 2_atlas_1", frames: [[150,404,135,400],[146,1187,139,395],[424,0,127,398],[287,402,131,398],[0,1187,144,400],[0,403,148,390],[420,1202,125,397],[287,802,131,398],[287,0,135,400],[146,1584,139,395],[420,802,127,398],[287,1202,131,398],[0,1589,144,400],[0,795,148,390],[420,1601,125,397],[287,1602,131,398],[150,0,135,402],[547,1202,125,397],[420,402,131,398],[0,0,148,401]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.currentSoundStreamInMovieclip;
	this.soundStreamDuration = new Map();
	this.streamSoundSymbolsList = [];

	this.gotoAndPlayForStreamSoundSync = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.gotoAndPlay = function(positionOrLabel){
		this.clearAllSoundStreams();
		var pos = this.timeline.resolve(positionOrLabel);
		if (pos != null) { this.startStreamSoundsForTargetedFrame(pos); }
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		this.clearAllSoundStreams();
		this.startStreamSoundsForTargetedFrame(this.currentFrame);
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
		this.clearAllSoundStreams();
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
		this.clearAllSoundStreams();
	}
	this.startStreamSoundsForTargetedFrame = function(targetFrame){
		for(var index=0; index<this.streamSoundSymbolsList.length; index++){
			if(index <= targetFrame && this.streamSoundSymbolsList[index] != undefined){
				for(var i=0; i<this.streamSoundSymbolsList[index].length; i++){
					var sound = this.streamSoundSymbolsList[index][i];
					if(sound.endFrame > targetFrame){
						var targetPosition = Math.abs((((targetFrame - sound.startFrame)/lib.properties.fps) * 1000));
						var instance = playSound(sound.id);
						var remainingLoop = 0;
						if(sound.offset){
							targetPosition = targetPosition + sound.offset;
						}
						else if(sound.loop > 1){
							var loop = targetPosition /instance.duration;
							remainingLoop = Math.floor(sound.loop - loop);
							if(targetPosition == 0){ remainingLoop -= 1; }
							targetPosition = targetPosition % instance.duration;
						}
						instance.loop = remainingLoop;
						instance.position = Math.round(targetPosition);
						this.InsertIntoSoundStreamData(instance, sound.startFrame, sound.endFrame, sound.loop , sound.offset);
					}
				}
			}
		}
	}
	this.InsertIntoSoundStreamData = function(soundInstance, startIndex, endIndex, loopValue, offsetValue){ 
 		this.soundStreamDuration.set({instance:soundInstance}, {start: startIndex, end:endIndex, loop:loopValue, offset:offsetValue});
	}
	this.clearAllSoundStreams = function(){
		this.soundStreamDuration.forEach(function(value,key){
			key.instance.stop();
		});
 		this.soundStreamDuration.clear();
		this.currentSoundStreamInMovieclip = undefined;
	}
	this.stopSoundStreams = function(currentFrame){
		if(this.soundStreamDuration.size > 0){
			var _this = this;
			this.soundStreamDuration.forEach(function(value,key,arr){
				if((value.end) == currentFrame){
					key.instance.stop();
					if(_this.currentSoundStreamInMovieclip == key) { _this.currentSoundStreamInMovieclip = undefined; }
					arr.delete(key);
				}
			});
		}
	}

	this.computeCurrentSoundStreamInstance = function(currentFrame){
		if(this.currentSoundStreamInMovieclip == undefined){
			var _this = this;
			if(this.soundStreamDuration.size > 0){
				var maxDuration = 0;
				this.soundStreamDuration.forEach(function(value,key){
					if(value.end > maxDuration){
						maxDuration = value.end;
						_this.currentSoundStreamInMovieclip = key;
					}
				});
			}
		}
	}
	this.getDesiredFrame = function(currentFrame, calculatedDesiredFrame){
		for(var frameIndex in this.actionFrames){
			if((frameIndex > currentFrame) && (frameIndex < calculatedDesiredFrame)){
				return frameIndex;
			}
		}
		return calculatedDesiredFrame;
	}

	this.syncStreamSounds = function(){
		this.stopSoundStreams(this.currentFrame);
		this.computeCurrentSoundStreamInstance(this.currentFrame);
		if(this.currentSoundStreamInMovieclip != undefined){
			var soundInstance = this.currentSoundStreamInMovieclip.instance;
			if(soundInstance.position != 0){
				var soundValue = this.soundStreamDuration.get(this.currentSoundStreamInMovieclip);
				var soundPosition = (soundValue.offset?(soundInstance.position - soundValue.offset): soundInstance.position);
				var calculatedDesiredFrame = (soundValue.start)+((soundPosition/1000) * lib.properties.fps);
				if(soundValue.loop > 1){
					calculatedDesiredFrame +=(((((soundValue.loop - soundInstance.loop -1)*soundInstance.duration)) / 1000) * lib.properties.fps);
				}
				calculatedDesiredFrame = Math.floor(calculatedDesiredFrame);
				var deltaFrame = calculatedDesiredFrame - this.currentFrame;
				if((deltaFrame >= 0) && this.ignorePause){
					cjs.MovieClip.prototype.play.call(this);
					this.ignorePause = false;
				}
				else if(deltaFrame >= 2){
					this.gotoAndPlayForStreamSoundSync(this.getDesiredFrame(this.currentFrame,calculatedDesiredFrame));
				}
				else if(deltaFrame <= -2){
					cjs.MovieClip.prototype.stop.call(this);
					this.ignorePause = true;
				}
			}
		}
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_25 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_24 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_23 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_22 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_21 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_20 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_19 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_18 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_17 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(8);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_16 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(9);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_15 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(10);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_14 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(11);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_13 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(12);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_12 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(13);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_11 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(14);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_10 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(15);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_8 = function() {
	this.initialize(img.CachedBmp_8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1894,4078);


(lib.CachedBmp_9 = function() {
	this.initialize(img.CachedBmp_9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1860,4091);


(lib.CachedBmp_6 = function() {
	this.initialize(img.CachedBmp_6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1894,4078);


(lib.CachedBmp_5 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(16);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_4 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(17);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_3 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(18);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_2 = function() {
	this.initialize(ss["ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"]);
	this.gotoAndStop(19);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_1 = function() {
	this.initialize(img.CachedBmp_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1594,4329);


(lib.Símbolo1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000CC").s().p("ABFFLQgigLgSgbQgSgcABgjQACgkAXgYQAPgPAogWQAlgVAigZQhnAAgjgBQgegBibgMQhygIhJADQguABgPgBQgigCgYgNQgWgMgOgWQgPgVgBgZQgCgZAMgYQALgXAWgOQATgMAbgFQASgDAhAAQBdgCB1AGQBGADCLAKQghgTgRgNQgbgUgMgYQgJgUgBgXQAAgWAJgVQAJgUARgOQARgPAVgGQAhgJApAOQAeALAnAZIBrBIQA/ApAxAUIA0ATQAdAMATAOQAWARAOAYQAJAOAEAPQAMASAEAXQAEAWgHAWQgQAxhKApQgWAMgKAHQgTANgkAhQgiAggWANQgKAGgWAKIggARIguAgQgcAUgWAGQgPAFgPAAQgRAAgSgGg");
	this.shape.setTransform(53.1141,33.712);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,106.3,67.5);


(lib.muñecodefrente = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.CachedBmp_10();
	this.instance.setTransform(0,0,0.5,0.5);

	this.instance_1 = new lib.CachedBmp_11();
	this.instance_1.setTransform(5.85,4.55,0.5,0.5);

	this.instance_2 = new lib.CachedBmp_12();
	this.instance_2.setTransform(2.45,8.25,0.5,0.5);

	this.instance_3 = new lib.CachedBmp_13();
	this.instance_3.setTransform(9.2,11.15,0.5,0.5);

	this.instance_4 = new lib.CachedBmp_14();
	this.instance_4.setTransform(16.9,12.7,0.5,0.5);

	this.instance_5 = new lib.CachedBmp_15();
	this.instance_5.setTransform(17.2,15.7,0.5,0.5);

	this.instance_6 = new lib.CachedBmp_16();
	this.instance_6.setTransform(13.35,19.85,0.5,0.5);

	this.instance_7 = new lib.CachedBmp_17();
	this.instance_7.setTransform(21.15,25.35,0.5,0.5);

	this.instance_8 = new lib.CachedBmp_18();
	this.instance_8.setTransform(14.25,27.2,0.5,0.5);

	this.instance_9 = new lib.CachedBmp_19();
	this.instance_9.setTransform(20.05,31.75,0.5,0.5);

	this.instance_10 = new lib.CachedBmp_20();
	this.instance_10.setTransform(16.7,43.2,0.5,0.5);

	this.instance_11 = new lib.CachedBmp_21();
	this.instance_11.setTransform(22.15,45.4,0.5,0.5);

	this.instance_12 = new lib.CachedBmp_22();
	this.instance_12.setTransform(31.15,46.35,0.5,0.5);

	this.instance_13 = new lib.CachedBmp_23();
	this.instance_13.setTransform(26.3,48.7,0.5,0.5);

	this.instance_14 = new lib.CachedBmp_24();
	this.instance_14.setTransform(21.8,52.2,0.5,0.5);

	this.instance_15 = new lib.CachedBmp_25();
	this.instance_15.setTransform(21.15,56.4,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},3).to({state:[{t:this.instance_2}]},3).to({state:[{t:this.instance_3}]},3).to({state:[{t:this.instance_4}]},3).to({state:[{t:this.instance_5}]},3).to({state:[{t:this.instance_6}]},3).to({state:[{t:this.instance_7}]},3).to({state:[{t:this.instance_8}]},3).to({state:[{t:this.instance_9}]},3).to({state:[{t:this.instance_10}]},3).to({state:[{t:this.instance_11}]},3).to({state:[{t:this.instance_12}]},3).to({state:[{t:this.instance_13}]},3).to({state:[{t:this.instance_14}]},3).to({state:[{t:this.instance_15}]},3).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,96.7,256.4);


(lib.muñeco = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000CC").s().p("Aj4PSQgtAAgfgJQgegJgsgdQg0ghgVgJQgSgJgEgFQgLgPAKgdQANgmAUgkQgEgCgCgFQgCgFADgEQAEgJAMgBQAGgBANAEIAmAOQAXAIARABQAVAAAFACQAJADAIAKQAIAIAIAPIAPAZQAGALALAOQAGAHAGADQAGAEAQgBQA6gCAdATQAUANAFASQADAPgIAQQgHAPgPAJQgVANgpADIghABIgKAAgAm9L7IgCAEQgPAlgMAhQgGAOAFAHQACACAIAEQApASAjAXQAkAYAMAFQASAHAmAEIAoADQATAAAvgGQASgEAFgCQANgIAAgKQABgLgJgIQgIgGgLgCQgYgHgoACIgOABQgIgBgGgCQgIgEgKgKIgXgcIgNgWQgHgPgGgIQgGgHgFgDQgGgBgGABQgTAAgZgIIgqgQIgEAAIgDAAgAClO4QgHgEgIgNIgwhOQgKgQABgJQAAgTAfgRIBbgyQARgKALgCQAMgDAUACIA4AJQANABAGgCQAEgBANgJQAegVAkAAQAYAAAUAKQAWALAKATQALAVgHAQQgFANgUAOQgtAehQAjIibBFQgRAIgMAAQgIAAgGgEgAD4L7QgIACgQAIIhsA9QAeAnAZAqQAEAHAEABQADABAHgDQA3gXAqgTIBFgeQA/gaA6gnQAHgFABgEQABgGgDgFQgFgKgMgGQgYgNgeAIQgYAGgaATQgKAHgGAAIgNgFQgEgCgOgCIg0gEIgOABgABSL6QgCgEgCgPQgCgLgHgVIgSgyQgQgtgJgVIgdg/QgSgmgJgZQgFgLAAgJQAAgJAJgUQALgZAGgeIgFgFQgFgHAAgIQgLgDgJgNQgLgOgDgSQgDgSAEgRIAHgTQAHgOAGgHQAUgVAqgCQAOgBAJACIAOAGIgDgIIAAgBQgSgngRg0IgihxIgKgiIgFgjQgCgXgEgMIgNglQgGgWAEgQQACgKAHAAQAFABAEAJIAQAsQALAmAEAZIADAeIALAjIA/DJQAFAQgCAKIACAGIAAABQARALAIALQANATAAAiQAAAXgHAMQgDAHgHAHIAAABQAGAlAQA/QAUBQAMAnQANAoAeBOQAEAOgDAGQgDAEgLAFQgeALgaAVIgNALQgJAGgGADIgFABQgCAFgGACIgDAAQgIAAgFgJgAgHGwQgEAJAAAFQAAAFADAIQANAoAUAlIAaAvQAIATANAnIAhBjIABAFQAqgeAvgPQg0h3gpicQgKgkgEgbQgMAHgMADQgIADgLAAIgUAAIgPgBQgHAcgKAegAALDjIgSAHQgIAEgDAFIgJAPIgFAJIgBAJQgBAZAHANQADAHAIAIIAEAEIAKABIAOAEIAMABIAOAAIAOgCQAHgBAJgEQATgKAFgLQAEgJgBgQIgBgIIgBgGQgCgJgEgGQgEgGgTgNQgNgIgEgBQgGgCgNgBIgIAAIgJABgAlzLaQgWAAgegDQgLgBgFgGQgFgHAFgOQAHgSAQglQAQgkAGgTQAGgRAJgkIAkiKQAHgbAIgJIASgRQAMgPAIgGIgCgDIgIgRQgBgEAAgVQgBgSACgJQABgHAGgMQALgUAOgMIgBAAIhNkZQgFgPAAgKQAAgKAGgQQAJgcAQglQAHgPAJACQAJADgCAQQgCAMgGASIgLAeQgMAlAGAZQABAIAKAYQALAcAKAyQALA6AHAWIALAgQAFATgBAOIgCAIIALgHQASgJAfgBQAxgBAcAUIANAKIAJAKIgXiGIgGglQgEgagBggIgGhrQAAgQACgGQADgGAIgGIAOgJIALgJQAHgEAFACQAFABACAFQACAFgBAFQgCAIgKAIIgMALQgDAFABAKIACBKIADA9IAEAjIATCrQAAAKgDACQgCADgDABQADAMgCAPIgDAXIgEAQQgCAFgGAKIgBADIgBAFQgBAFgGAIQgtA/gyBTQgfAzg5BjIgnBFQgIAOgGADQgGAFgNAAIgFgBgAkkFuQgNANgDAGQgEAGgDAKQgPAygZBlQgZBageA4QAOADAPACQALABAFgCQAIgEAHgNIBmi2QAeg1A7hSQgVAGgXgCQgbgCgagOQgLgGgIgHQgHANgKAKgAjUDSIgTAFQgKAEgFAEQgGAEgIAMIgIAMQgDAIAAAPQAAATAEAJQAFAOAPAKQALAHASAFIATAEQAWABATgHIAQgIQANgJAJgOQgEgFABgJIAEgPQAFgWgHgOQgEgGgKgIQgOgKgLgDQgMgEgUAAIgUABgAmUhaIg7gbQgRgNgKgFIgQgHQgJgGAAgHQAAgEAFgIIAUgjQASggAQgPQAFgFAEgCQAIgDANABIABAAIAAgCIgBgdQgBgSABgKIABgLIAAgbIAAgCIgBgFQgBgBgFgEQgDgEAAgEIgBgHIgEgEQgCgDgBgHQAAgMABgFQADgJAHgFQAEgCAHgBQABgDADgEQAWgmAPgjQACgGADgCQAFgEAEAEQADADgDAIQgUAsgUAjIACABQAFACAHAJIAFAKQABADAAALIAAAPQgCALgRAIIAAABQABAZgCAMIgCAMIgBAqIAAAJIAhABQAKABADAEQAEAEAAAKQAAAoAHAUQADALgBAEQAAACgIAJQgDAEgEAJIgIANIgHAJQgFAFgBAFIgCAKQgCAHgFABIgCAAIgHgCgAmzjuQgCABgDADQgNAOgJAQIgFAJQgKASgKANQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABIADADQAMAGAHAGIAZASQARALAVAGIAdgzIACgFQAAgCgCgGQgGgSAAgsIgugBIgIgBIgBAAgAmnmXIAAAEIABAHIAEAEIACADIACABIADACIADACQABgBAAgEQABgGgDgIIgCgEQgDgCgFAAIgBAAgABSjMQgGgBgJgGQgmgZgUgQQgFgFgCgEIAAgKQAGgTAKgPIgCgBIgMgCIhhgKIgTgBIgLgCIgCAGQgDAFgIADQgRAIgOgFQgLgEgKgOQgHgKABgJQAAgGAEgEQADgDADgBIgghAIgMgVIgRgaIgCAAQgUAIgWgBQgXAAgOgKQgKgGgJgPQgKgQgCgRQgCgRAIgNIACgDIADgFIABgGQACgHAHgJIALgPQAOgMAggEQAdgFAQAGQAJAEAJAIQAQAOAHASQADAIABAIQABANgDANQgFAWgQAQIgJAJIADAFIAQAWQAGAIAKATIAeA6IAEAIIADAAQAGAAAFADIAEADQAFAFACAIIACADIACgBQAZgBAjADIA7AHQAUACAMADQAAgGACgDQAEgLAIADIAIAFQADACAFAAIAIAAIANACQAJACAEgBIALgCQAFAAAGAFQANAKANAUQAGAIABAFQADAKgJAQQgIASgMASIgJAKQgFAFgLADQgHACgFAAIgCAAgABPlBQgIABgXAAIgCAFQABADgBADQgCAFgDACIgBAAQgDAGgCABIgFADQgBACgBAFIgDAHQgBABAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABQABAAAAABQAAAAAAAAQABABAAAAQAMALASAMIAZATQAFADACABIAIAAIAIgDIAFgGIANgTQAIgMADgJQACgDAAgFQgBgDgEgFIgVgcIgGgEQgCgCgFAAIgQADgAiblEIAJABQAEAAACgCQADgDgDgGIgBgEQgCgGgDgCIgFAAIgBAEQgDAFgGACQgEABgDgBQAGAJAHACgAkmpOQgLAEgDACQgFACgJAKIgMAPIABAEIAAABQABAFgBALQgCATASAUIAHAHQAEACAGABQALADAJAAQAQAAAPgIQAVgKAJgVQAGgPgDgPQgCgHgDgHIgHgJQgGgHgEgDQgLgIgQAAQgKAAgTAEgAkVjpQgSgDgIgHQgHgGgHgTIgQg1IgKgkIgJggIgIgpQgHgYAIgIQADgEAEABQADAAAEAEQAHAHAEAVQAGAeANAuQALAlAQAwQABAEADAEQADADAIACQBeASBagIQAXgCAGgKQABgDABgLIABgVQAAgIACgDQAEgGAGABQAEACABAJQACAKgBAPQgBAPgFAJQgLAUgnAFQgdAEghAAQg1AAhDgKgAgzlZIgCgKIAAgCIgEgRQgBgDAAgOIAGiIIAAgaQAAgfgEgSQgKgrgcgVQgIgFgCgEQgCgDAAgDQAAgEADgCQAFgDAHADQAYAIAPAWQAHAKAHAQQAIAVACALQABALAAAVIAAAOIgCBmIAAAGIACAnQABARgDALIgEAVIgBADIgCAJQgCAGgGAAQgEAAgDgGgAlkpIQgIgCAAgJQAAgFAEgJQAMgWAlgcIAQgMQALgGANgGIAngPIAQgEIACAAIAAAAIAEgPQABgHgBgDIgCgLQgBgGABgEQACgEAFgCQAGgCAEADQAEADADAHQABgFAHABIAJAGQAQAOAQAEQAJACATgBQAVgCAJgIQAHgHACgMQANgxgcg6QgEgJAAgFQAAgEADgDQACgEAEAAQADAAAFAEQAFAFAEAIQAbAxgHA3QgDAkgUAQQgPALgaACQgSACgOgDQgSgEgLgLIgPgVIgBgBQAFASgIASQgEAHgEADQgHAEgFgDIgHAEIg2AbQgUALgYAVIgMALQgHAHgDAIIgIALQgEAFgFAAIgDgBgAiXqJQgWgDgNgUQgEgJAFgDQAEgDAHAGQAMAKAHACQAMAEAKgFQAHgDABgDIAEgJQAFgEAFAGQADADgCAHQgCAHgGAGQgMALgRAAIgEAAgAjXryIgFAAQgHACgFgCIgMgCQgPgFgFgKQgEgHABgLQACgUAMgJQgEABgFgDQgDgBgCgEIgMgPIgLgTIgEgKIgCgIQAAgLACgKQACgKAEgFQADgDAFgBQAEgBAEACQAFADABAIIgBANIAAAHIABAGIACAHQAIAPAHAJQAFAHABADQAFAJgHAHIgBABQAFgDAGABQAKAAAGAHQAEAEAAAGQgBAIgIADQgIADAAACQAIACAFADIAEAEQAFAAADABQAEADABAEQACAEgCAEQgBAFgGADIAAABIgDAHIgBACQgCgEAAgDgAh/sqQgGgCgBgIQAAgGAGgEIAEgBIABAAQAIAAACAHQADAHgFAFQgEADgEAAIgEgBgAictjQgJgBgFgDIgGgDIgHgBQgEAAgCgCQgCgCABgEQABgGAHgDQAFgCAHACIAMAFQAIADARgDQALgCAFgDQAEgDADgGQADgFAAgFQgBgHgFgGQgIgIgQgLQgIgGgGgCIgPgFQgJgEABgIQACgHALgCQAPgCATAJQARAHAKAJQAHAGAJANIAEAKIABALQgBAKgDAGIgDAEIADABIgJAIQgEAEgKAGIAAgBQgRAKgVAAIgMgBgAj4t/IgIgHQgIgGgCgFQgCgDAAgEQABgEACgCQAEgDAHACIAJAFIAKAGQADADADAFQADAFgBAFQAAADgDACQgDADgDAAQgFAAgHgFgAjVuNIgHgFQgEgEgIgDIgMgGQgGgDgBgEQgBgHAKgDQAEgBAJABQAJABAGAEQAHADADADQAEAGAAAGQAAAFgDAFQgDADgEAAIgDgBgAiuugIgFgGQgDgFgIgGQgGgEgLgDQgIgCAAgEQABgEAHgBQAHgCAGABQAJABALAIQAHAEAEAGQAFAIgEAHQgBADgDABIgCAAQgCAAgEgCg");
	this.shape.setTransform(51.5743,97.8631);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0000CC").s().p("ADlO8IiogSQgfgEgJgOQgDgIAAgPIgDhbQgBgTAFgIQAKgPAjAAIBnACQAVAAAKAEQAMAEAQALIAsAjQALAIAGACQAFABAPgCQAkgDAgASQAUAMANATQANAUgBAWQAAAXgPALQgKAIgYADIggABQguAAhAgHgAAtN7QAAAHADADQACADAHABQA8AIAuADIBLAJQBDAKBGgGQAIgBADgDQAFgEgBgFQABgLgIgMQgOgXgegJQgXgGggADQgNABgFgDIgJgKQgDgEgLgJIgrgdIgNgHQgHgCgSgBIh7gBQAGAxAAAxgAjNPBQgMgBgTgPQgqglg2hEIhqiDQgUgZAEgQQADgIALgLIA+hDQANgOAJgBQASgEAYAYIBIBLQAPAPAEAKQAGALAEASIAGA5QACANADAGQADAEALAJQAcAYAKAjQAGAWgFAXQgFAYgQAPQgNAOgQAAIgGgBgAmhKYQgFAFAAAEQAAAEAEAFQAlAwAeAjIAvA8QApA2A0AtQAHAFAEAAQAHABADgEQAIgIADgNQAGgbgOgbQgMgVgZgUQgLgJgBgGIABgNQABgFgBgOIgKgzIgFgOQgDgHgNgNIhWhYQgeAngjAjgADcLDQgfgIghADIgRABQgKAAgIgBIgEgCQgFADgGgCQgJgEABgMQABgEAGgOQAFgKAGgVIAOg0QAMguAEgXQAEgQAHg0QAGglAGgYIgBAAIgDACIgDAEQgDAEgLAEIggAPIgCABIgGADQg1Abg8AhQg1AchiA7IhEAnQgPAIgHAAQgIAAgPgJQgSgKgYgSQgKgHgBgHIAAgBQgBgHALgJIABgBIAhgaIANgKIABgBQAggWAPgOIAngnIBkhlQAUgUALgEIAZgFQAQgHAKgBQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQABgMACgFQABgFAKgSQAIgRAHgGQAEgGAMgHQATgLASgEIgBgBIABgFIACAAQgJgRgIgcIgRgzQgUg3g1hEQgLgPgBgFQgCgFAAgVIgCgdQgBgjAOgiQADgHAFgCQAEgBAEAFQADAEABAFQABALgDASQgDAVAAAIIADAbIAAAOIABANQABAGAIAQQAXAhAVAnQAMAUAGARIANApIAUBHIABAJIAHgBQAVACAaAPQAsAXAOAfIAFAOIABgJQACgeACgPIAJguIgCABIAAgDIACAAIAAgBQACgMABgmIAEhHIADgvQAGhDAEgaQABgGACgCQAEgFAEACQADACABAGQADAPgCAZIgHCxQgCAvgFAXIgHAlQgCAPgBAeIgCANIgCADQgEAFgBAKQgBANgBADIgFAMIgEALIgMAIIgBABQgJAEgDAFQgDAEgCAIQgLAqgEAqIgGA1QgDAUgLAoIgeBkIgBAFQAzgCAwAPQAYiAA2iYIAOgjIAKgYIAFAAIgNgBIgSgHIAAgBIgFgGQgEgHgBgIQgKgCgKgNQgKgOgDgSQgEgSAFgRIAHgTQAGgOAHgHQATgWArgCQAPgBAJADIANAFIgCgHIgBgCQgRgmgRg0IgkhxIgJgjIgFgjQgDgWgDgNIgNglQgHgWAEgPQACgKAIAAQAEAAAFAJIAQAtQAMAmADAYIAEAfIALAiIA+DKQAGAPgCALIABAGIAAAAQARALAIALQANATAAAjQAAAWgGANIgEAGQgFACgFAGIgGAJIgEADIgKAGIAAAAIgFADQgUAJgZABIAGACIgRAkIgVA2QgcBOgMAnQgMAogUBRQgEAOgGADQgCABgEAAIgLgBgAgSFJQgRAEgGAEQgHAEgHAGQgmAkhIBMQhDBAg2AjIAXASQAJAGAGABQAHABAOgHICzhsQA0geBbgqQgUgFgUgNQgWgQgPgYQgIgMgCgJQgMAHgOAEgABdDkQgIAAgMAHIgNAGQgHAGgIANQgJAQgCAKQgCAOAIAQQAGANAOAMQAEAFAKAIQATAMATAEIASABQAQgBAPgIQgBgHAGgHIAKgLQAQgQAAgQQAAgHgFgMQgHgQgIgIQgJgJgRgLIgRgJIgTgEIgNgCIgEABgAFFDTIgUAHQgHAFgEAFIgJAPIgEAIIgBAJQgBAaAGAMQAEAHAHAJIAEAEIALAAIAOAEIANABIAOAAIAOgBQAHgCAIgEQATgKAFgLQAEgIgBgQIAAgJIgCgGQgCgJgDgFQgEgHgUgMQgNgIgDgBQgGgCgNgBIgIgBIgJABgAEnFeIAAgBIAIAEIgIgDgAB1geQgIglgDgXQAAgIABgEIAIgHQARgJASgEIgBgBQgBgDgGgIIgSgWQgFgLgPgPIgEgEIgUgYIAAgBIgygGQgTgDgIgHIgDgDIgBgHQgEgJgEgFIAAgBIgQg1QgOgsgFgYIgJgpQgGgYAIgIQADgEAEABQADAAAEAEQAGAHAEAVQALA0AfBiIABgNQACgNAHgFQAFgEAFAAIAEABIgBgFIgDgSIgEgkIgBgbIgDgWIgFgYIgBgKIgEAAQgVAAgOgKQgKgGgJgPQgLgQgCgRQgBgSAHgMIACgDIADgFIACgGQABgHAHgJIAMgPQAOgMAfgEQAdgFAQAGQAJAEAJAIQAQAOAGASQADAIABAIQACANgEANQgFAWgPAQIgKAJIABABIgLAHIgMAIIgBgCIgDAAQgHADgJACIAEAXIADAUIABAXQgBAOABAGIACAPIACAVIACAUIACAKIgBAEIAMAMIADABQAEAGgBAGQABAGgFAIIgBADIADABIALALQBDAIBCgGQALgBAHgDIAAgEIAFgFQADgEACgIIAEgSIAAgBQAEgUAAgKIgCgaIgBgcIgCAAIgBgOIAHiIIAAgaQgBgfgEgSQgJgrgcgVQgIgFgCgEQgCgDAAgDQAAgEACgCQAFgDAIADQAYAIAPAWQAHAKAGAQQAIAVACALQACALAAAVIAAAOIgCBmIgBAGIACAnQABARgCALIAAABIgCAAIACARQACAbgBAQQgBAYgHASIgFANIgFAKQgLAUgnAFQgQACgSABQgDgCgFAAIgLAAIgKgBIgHAEIgIABIACgCIgagBIAFAHIAlAvIAUAaIAIgFQAKgEAEAHIACAJQABAEAEADIAGAGIAHALQAFAHAEACIAJAHQADADABAIQABAMgCAQIgBALIAAAAIgDAFIgCACIgEAOQgGAFgNAEQgSAFgVAEIgKABgACPhlIgHADIgEACQAAAAAAABQAAAAgBAAQAAABAAABQAAAAAAABQABAQAEAUIAEAgIACAIIAGAFIAHAEIAIgBIAXgEQAOgCAJgFQADgBADgDQACgDABgGIAEgjIAAgHQgBgDgDgDIgNgKQgHgEgQgRIgFACIgFAFQgEACgEgBIgBAAQgGABgCgBIgGAAIgGACgAAokCIAGAHQADADADAAQAEAAACgGIACgEQADgGgBgDIgDgEQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgFACgGgDQgDgCgCgDQgCALADAGgAANo+QgMAEgCACQgFACgIAKIgMAPIABAEIAAABQABAFgCALQgBATARAUIAHAHQADACAHABQALADAIAAQARAAAPgIQAVgKAIgVQAGgPgDgPQgBgHgEgHIgGgJQgGgHgEgDQgMgIgQAAQgJAAgTAEgAHBkUIAAgDIgCgFIABABQAGAIABAFIABAGIgHgMgAgxo4QgHgCAAgJQgBgFAFgJQAMgWAlgcIAPgMQAKgGANgGIAogPIAPgEIACAAIAAAAIAFgPQABgHgBgDIgDgLQgBgGACgEQACgEAFgCQAFgCAEADQAFADADAHQABgFAGABIAJAGQARAOAQAEQAJACASgBQAWgCAIgIQAHgHADgMQANgxgcg6QgEgJAAgFQAAgEACgDQADgEADAAQAEAAAEAEQAFAFAEAIQAcAxgHA3QgEAkgUAQQgOALgaACQgTACgOgDQgSgEgKgLIgPgVIgBgBQAEASgIASQgDAHgFADQgGAEgGgDIgGAEIg3AbQgTALgYAVIgMALQgGAHgEAIIgHALQgFAFgEAAIgEgBgACcp5QgXgDgMgUQgFgJAFgDQAEgDAHAGQAMAKAHACQAMAEALgFQAGgDACgDIADgJQAFgEAFAGQAEADgCAHQgCAHgGAGQgNALgQAAIgEAAgABcriIgFAAQgHACgGgCIgMgCQgOgFgGgKQgDgHABgLQACgUAMgJQgFABgEgDQgDgBgDgEIgMgPIgLgTIgEgKIgBgIQgBgLACgKQACgKAFgFQADgDAEgBQAFgBADACQAFADABAIIAAANIgBAHIABAGIADAHQAHAPAHAJQAGAHABADQAEAJgHAHIAAABQAFgDAGABQAJAAAGAHQAEAEAAAGQgBAIgHADQgIADgBACQAIACAGADIAEAEQAFAAACABQAEADACAEQABAEgBAEQgCAFgGADIAAABIgDAHIAAACQgCgEAAgDgACzsaQgGgCgBgIQAAgGAGgEIAFgBIABAAQAHAAADAHQACAHgFAFQgDADgEAAIgFgBgACWtTQgIgBgFgDIgHgDIgHgBQgEAAgCgCQgCgCABgEQACgGAGgDQAGgCAGACIAMAFQAIADASgDQALgCAEgDQAFgDACgGQADgFAAgFQAAgHgGgGQgHgIgQgLQgIgGgHgCIgPgFQgJgEACgIQABgHALgCQAPgCATAJQASAHAJAJQAIAGAIANIAFAKIAAALQgBAKgDAGIgCAEIACABIgIAIQgFAEgKAGIAAgBQgRAKgUAAIgNgBgAA7tvIgJgHQgIgGgCgFQgCgDABgEQAAgEADgCQAEgDAGACIAKAFIAKAGQADADACAFQAEAFgBAFQgBADgCACQgDADgEAAQgEAAgHgFgABet9IgIgFQgEgEgHgDIgNgGQgGgDAAgEQgCgHAKgDQAFgBAJABQAIABAGAEQAHADADADQAFAGAAAGQAAAFgEAFQgCADgEAAIgDgBgACFuQIgFgGQgEgFgIgGQgGgEgLgDQgHgCAAgEQAAgEAHgBQAIgCAGABQAJABALAIQAGAEAFAGQAEAIgDAHQgCADgDABIgBAAQgCAAgEgCg");
	this.shape_1.setTransform(67.8112,99.4289);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0000CC").s().p("ACxPXIipgKQgegCgKgOQgEgIAAgPIgIhbQgBgTAFgIQAJgQAigBIBogCQAUgBAKADQAMADARALIAtAhQAMAHAGACQAEAAAQgCQAkgEAgAQQAVALANATQAOATABAWQAAAXgOAMQgKAIgYADQgcAEgmAAQgiAAgpgDgABmM5Ih6AEQAJAwACAxQAAAIADADQACACAHABQA7AFAvACIBLAFQBEAGBFgIQAIgBADgDQAEgFgBgFQAAgLgHgLQgPgXgfgHQgXgFghAEQgMACgFgDIgJgKQgEgEgLgIIgsgcQgJgEgEgBQgHgCgNAAIgGAAgAgdMSQgHgFAAgPQgBgTABgoQACgngBgVQgBgSgFglIgTiNQgCgXADgMIAfgCIgEAMQgBAIABAJQAFA0AOBoQAKBdgHA/QANgCAOgFQALgDAEgDQAGgHABgOIAcjQQAGgtAQhCIANgCIAQgDQgJAqgIAvQgKA7gQBxIgKBOQgDAQgEAGQgGAHgQAFQgUAIgbAIIgKACQgFAAgDgCgAl/KOQgIgKgDgYQgHg3AGhXIAKioQACggAOgJQAIgEAPgBIBbgHQATgCAIAFQAQAJABAkIACBnQABAUgDALQgDAMgLAQIghAuQgHALgCAGQAAAFACAPQAEAkgQAgQgLAVgTAOQgTAOgWAAIgBAAQgWAAgMgNgAlSEjQgIABgDADQgCACgBAHQgFA8gCAuIgFBLQgGBEAIBGQABAIADADQAFAEAFgBQALAAALgHQAXgQAHgfQAFgXgEggQgCgNADgFIAKgJQAEgDAIgLIAcgtQAEgIABgFQADgHgBgTIgEh7QgwAJgxACgAiZGKQgEgDgDgMQgIgfgSgbIgJgPQgFgJgCgHIgBgFQgFgDgBgGQgBgKAMgEQADgBAQgBQALgBAVgFIA0gMQAvgKAWgIQAQgEAwgSQApgOAZgFIgCgGIgFgEIgCgFIgHgJIAEACIgFgKQgIgJgKgFIgCgEIgUgdIgYgeIgTgdQghg0gdg5IgGgKQgFgVgDgXIgBgIQACgKAFgMQAPghAVgfQAEgEACgBQADAAADACQAEADAAADQAAAFgEAJQgMAZgMAhQgFANAAAJQAAAKAHARQAcBAAXArQANAZAKAMIAXAYQAOAOAWAlIAQAaIAEAKIARALQAUARAcANIACgBIgGAIIgDAEIADgDIgHAKIgEgBQgRgJgSgMIgDAAQgFgBgIACQgqAKgnAPIgwAVQgUAGgoAJIhmAVIgFABQAZAsAKAxQB7gnCggXIAmgFIAPgBQgDgIgCgIQgDgSAEgRIAEgMIADgHIADgFIABgEIADAAIAFgLIABgBQAIgJALgFIABgCIADgCIAAABIgBACQARgIAYgBQAOgBAJADIAOAFIgDgHIAAgCQgMgZgLggIgFgCIgHgEIAEACIAHADIgLggIgjhxIgKgjIgFgjQgCgWgEgNIgNglQgGgWAEgPQACgKAHAAQAFAAAEAJIAQAtQAMAmAEAYIADAfIALAiIA/DKQAFAPgCALIACAGIAAAAQARALAIALIAFAJQAIARAAAcQAAAWgHANQgDAGgHAHIAAABIABAEIgQAKIgFADIgHAAIgSAKIgCABQgIACgLABIgUAAIgEAAQgTgDgMgLIgFgBIAAgBIgBgBQgEgHAAgHQgGgBgGgFQgOAAgSACQgbADgjAFQhSALgnAHQgqAJhQAVIgKABQgHAAgDgDgAD3DiIgTAHQgIAFgDAFIgFAHIgEAIIgFAIIgBAJQgBAaAHAMQADAHAIAJIAEAEIAKAAIAPAEIAMABIAOAAIAOgBQAHgCAJgEQATgKAFgLQAEgIgBgQIgBgJIgBgGQgCgJgEgFIgGgHIgRgMQgNgIgEgBQgGgCgNgBIgIgBIgJABgAhJDPIgBiyQAFgDAFgJQAIgNAFgIQABAzgFA0QgCAZADAZQABAVgCAYIgDAPgAhLhRIABgHIACAIQAGAWAIAUQgQgagBgRgAh3g6IABgDIAAADIgEAMIADgMgAiehDQgUgCgVgFIgMgFQgHgDgGgJQgFgHgCgFQgBgGADgLQAKgsAIgYQACgHAEgDQACgCAHgBQATgCARAEIAAgCIgYh2IgGgXQgCgHAAgHIgHABQgFgCgGgHQgNgRAAgTQAAgNAJgSQAIgNAIgDQAGgCAFADQAEACACADIAwhBQANgQADgHIANgUIAAgCIAEgJIACgDIADgFIACgGQABgHAHgJIAMgPQAOgMAggEQAcgFAQAGQAJAEAJAIQAQAOAGASQADAIABAIQACANgEANQgFAWgPAQIgKAJIgRALIgFABQgBAAgBAAQgBAAAAABQgBAAAAAAQAAABAAABIgCAAIgBgBIAAACQgRAGgVgBQgWAAgOgKQgKgGgJgPIgGgLIgDADIgBABIgBAOIgMAQIgrA7IgHAJIACAEQACALgDAJQgDAHgGAHIgDADIACACQAJAbAJApIAAADIAEATIAKA1IAFAVIACgBIAAAEIAJgCQALABABAIIgCAJQgBAEACAFIACAIQACADABAJQABAJADAEIAFAKQACAEgDAHQgEAQgOAUQgGAIgEADQgGAEgLAAIgKgBgAi5i3QgBAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAQgGAPgFAVIgJAeQgCAGABACIACAHQADAFADACQACACAFABIAXAGQANADAKAAIAIgCQADgBADgGIATgdIABgHQACgDgCgEIgIgPQgEgGgIgWIgGgBQgCACgDAAQgFABgDgDIgBAAIgIgDIgFgDQgCgBgEABIgIAAIgDgBIgBAAgAjJmKIADALQACAFACABQAEACAEgGIADgDQAFgFABgDIgCgGIgDgBQgGAAgEgHIgCgHQgHAKAAAJgAgqpVQgMAEgDACQgFACgIAKIgMAPIABAEIAAABQABAFgCALQgBATARAUIAHAHQAEACAHABQALADAIAAQARAAAOgIQAVgKAIgVQAGgPgDgPQgBgHgEgHIgGgJQgGgHgEgDQgMgIgPAAQgJAAgTAEgAFthYIhAgLQgUgJgKgCQgMgBgFgBQgLgEgCgHQgBgDADgJIAKgoQAKgjAKgTIAEgFIAEgDQAGgHANgCIABAAIAAgBIgJgcIgHgbIgCgLIgHgaQgBgFgCgBQAAgCgGgCQgFgEgBgDQgBgGgBgBIgFgCQgDgCgDgIIgDgQQAAgJAGgGIAbgHIAIACIAGAEIAIAJQACADADAKIAEAOQgBALgNANQAHAYACANIABAMIAKAoIABAFIABAEIAggHQAKgCAEADQAFACADALQAKAmAMASIAEAHIACAGIgCAEIgEAJQgCAEgBALIgEAPIgFAKQgDAGAAAFIABALQAAAGgFADQgBABgFAAIgDAAgAExjhQgHABgBABQgCABgCAEQgJARgFARIgCAKIgLAjQgBABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQAOADAIAEIAcALQAUAGAVABIAQg5IAAgGQAAgCgEgFQgKgQgLgqgAEMmJIgBAAIgCAEIABACIACAIIAFACIADACIACABQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAAAIAEACQABgCgBgEQgBgFgFgIIgDgEIgDAAIgFABgAgZjwQgTgDgIgHQgHgGgGgTIgQg1QgOgsgFgYIgJgpQgGgYAIgIQADgEAEABQADAAAEAEQAGAHAEAVQALA3AjBqQABAEADAEQADADAIACQBdASBbgIQAXgCAFgKQACgDABgLIABgVQAAgIACgDQADgFAEAAIACAAIABABQAEACABAIQACAKgBAPQgBAPgGAJQgLAUgnAFQgcAEgiAAQg1AAhBgKgADHlgIgBgKIgFgTQgBgDAAgOIAHiIIAAgaQgBgfgEgSQgJgrgcgVQgIgFgCgEQgCgDAAgDQAAgEACgCQAFgDAIADQAYAIAPAWQAHAKAGAQQAIAVACALQACALAAAVIAAAOIgCBmIgBAGIACAnQABARgCALIgGAYIgCAJQgCAGgFAAQgFAAgDgGgAhlozIABAAIgBABIAAgBgAhppPQgHgCAAgJQgBgFAFgJQAMgWAlgcIAQgMQAKgGANgGIAngPIAPgEIACAAIAAAAIAFgPQABgHgBgDIgDgLQgBgGACgEQACgEAFgCQAFgCAEADQAFADADAHQABgFAGABIAJAGQARAOAQAEQAJACASgBQAWgCAIgIQAHgHADgMQANgxgcg6QgEgJAAgFQAAgEACgDQADgEADAAQAEAAAEAEQAFAFAEAIQAcAxgHA3QgEAkgUAQQgOALgaACQgTACgOgDQgSgEgKgLIgPgVIgBgBQAEASgIASQgDAHgFADQgGAEgGgDIgGAEIg2AbQgTALgZAVIgMALQgGAHgEAIIgHALQgFAFgFAAIgDgBgABkqQQgXgDgMgUQgFgJAFgDQAEgDAHAGQAMAKAHACQAMAEALgFQAGgDACgDIADgJQAFgEAFAGQAEADgCAHQgCAHgGAGQgNALgQAAIgEAAgAAkr5IgFAAQgHACgGgCIgMgCQgNgFgGgKQgDgHABgLQACgUAMgJQgFABgEgDQgDgBgDgEIgMgPIgLgTIgEgKIgBgIQgBgLACgKQACgKAFgFQADgDAEgBQAFgBADACQAFADABAIIAAANIgBAHIABAGIADAHQAHAPAGAJQAGAHABADQAEAJgHAHIAAABQAFgDAGABQAJAAAGAHQAEAEAAAGQgBAIgHADQgIADgBACQAIACAGADIAEAEQAFAAACABQAEADACAEQABAEgBAEQgCAFgGADIAAABIgDAHIAAACQgCgEAAgDgAB7sxQgGgCgBgIQAAgGAGgEIAFgBIABAAQAHAAADAHQACAHgFAFQgDADgEAAIgFgBgABetqQgIgBgFgDIgHgDIgHgBQgEAAgCgCQgCgCABgEQACgGAGgDQAGgCAGACIAMAFQAIADASgDQALgCAEgDQAFgDACgGQADgFAAgFQAAgHgGgGQgHgIgQgLQgIgGgHgCIgPgFQgJgEACgIQABgHALgCQAPgCATAJQASAHAJAJQAIAGAIANIAFAKIAAALQgBAKgDAGIgCAEIACABIgIAIQgFAEgKAGIAAgBQgRAKgUAAIgNgBgAADuGIgIgHQgIgGgCgFQgCgDABgEQAAgEADgCQAEgDAGACIAJAFIAKAGQADADACAFQAEAFgBAFQgBADgCACQgDADgEAAQgEAAgHgFgAAmuUIgIgFQgEgEgHgDIgNgGQgGgDAAgEQgBgHAJgDQAFgBAJABQAIABAGAEQAHADADADQAFAGAAAGQAAAFgEAFQgDADgDAAIgDgBgABNunIgFgGQgEgFgIgGQgGgEgLgDQgHgCAAgEQAAgEAHgBQAIgCAGABQAJABALAIQAGAEAFAGQAEAIgDAHQgCADgDABIgBAAQgDAAgDgCg");
	this.shape_2.setTransform(73.231,94.9758);

	this.instance = new lib.CachedBmp_6();
	this.instance.setTransform(55.9,-7.2,0.0491,0.0491);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0000CC").s().p("AjpPhQgzgDgXgUQgIgGgKgNIgQgVQgQgTgjgTQgzgbgHgFQgRgLgDgNQgDgKAHgRQANgiATglQAHgPAJgEQAJgEATAGQAhAKAhACQAbABAIAFQAJAFAIANIALAXQAEAJANAUQAMASAFALIAHAOQAEAHAFAEQAIAFAPABQAmACAYAKQAiAOAOAaQAIAMAAANQAAAPgIAJQgJAKgXAEQguAJgzAAIgaAAgAmfLoQgDACgDAGQgRAjgNAhQgCAIABACQABAEAGAEQAMAHArAVQAiAQASAPQAQAOAOAUQANARAFAEQAHAEAOADQBBANBfgPQAJgDABgBQAGgHgHgMQgMgVgcgJQgQgGgigDQgZgCgMgHQgHgGgHgLIgKgVQgEgJgPgUQgMgTgFgLIgFgNQgEgHgEgEQgIgGgWAAQgmAAghgNQgGgDgEAAIgEABgADWOqQgHgFgIgNIgwhOQgKgQABgJQAAgSAfgRIBbgyQARgKALgCQAMgDAUACIA4AIQANABAGgBQAEgCANgIQAegVAkAAQAYAAAUAKQAWALAKATQALAUgHARQgFAMgUAOQgtAfhQAjIibBEQgRAIgMAAQgIAAgGgDgAEpLtQgIABgQAJIhsA8QAeAnAZArQAEAGAEABQADACAHgDQA3gXAqgUIBFgeQA/gZA6goQAHgFABgEQABgGgDgEQgFgKgMgGQgYgNgeAHQgYAGgaATQgKAIgGgBIgNgEQgEgCgOgCIg0gEIgOABgABqLrQgCgDgCgPQgCgLgHgVIgSgyQgQgtgJgWIgeg+QgSgngIgYQgFgMAAgJQAAgJAJgUQAKgZAGgdIgFgGQgFgHAAgIQgKgCgJgNQgLgOgDgSQgDgSAEgRIAHgTIAGgKIgBgBIgDgCIgBgDIgBgCIABgBQgJgMgJgLIghgfQhXhOgpg8IgYgkIgng9QgMgTgFgMIAAgCQgGgMAAgJQAAgLAGgTQAJgjARggQACgGACgBQAEgBADACQADACABAEQACAFgDAJQgJAagHAjQgCAOABAJIABAEIAGALQBFBtAtAyQATAWAeAdIAzAyQAdAdANAYIAHgEQAHgBAEgDQAFgDAEgDIABAAIAAAEIATgCQAOgBAJADIAOAFIgDgHIAAgCQgSgmgRg0IgjhxIgKgjIgFgjQgCgWgDgNIgNglQgGgWAEgPQACgKAHAAQAFAAADAJIAQAtQAMAmAEAYIADAfIALAiIA/DKQAFAPgCALIACAGIAAAAQARALAIALQANATAAAjQAAAWgHANQgDAGgHAHIAAABQAGAmAQA/QAUBQAMAnQANAoAeBOQAEAOgDAFQgDAFgLAEQgeAMgaAUIgNALQgJAGgGADIgFACQgCAFgGABIgDAAQgIAAgFgJgAAQGhQgEAJAAAFQAAAFADAIQAOApAUAlIAaAvQAIATANAnIAhBjIABAFQAqgfAvgPQg0h2gpidQgKgkgEgaQgMAHgMADQgIACgLABIgUAAIgPgBQgHAcgLAdgAALDaQgLAHgDAKQgCAGABAFIgEAGIgBAJQgBAaAHAMQADAHAHAJIAEAEIAKAAIAPAEIAMABIAOAAIAOgBQAHgCAJgEQATgKAFgLQAEgIgBgQIgBgJIgBgGQgCgJgEgFQgEgHgTgMQgNgIgEgBQgGgCgNgBQgLgBgGABIgDACIgGgBQgIAAgHAFgAldLMQgVAAgegEQgMgBgEgFQgFgHAFgOQAGgTAQgkQAQgkAHgTQAGgSAJgkIAjiKQAIgaAIgKIASgRQALgOAIgGIgCgEIgHgQQgBgEAAgWQgBgSACgJQABgHAGgMQALgTAOgMIgBgBIgBgCIAIgEQgDgKgBgLIAAghQAAgVgHgrIgOhMQgCgPACgFQACgFAFgCQAFgDAEADQADACADAGQAGAOAGAlIAIBAIAEATQABAJAAAaQgBAVADANQAQgGAWAAQAygBAbATIANALIAHAGIAFAMIABAKQABAFACAEQACAEAEADIABAAIAAASIgEAWIgEAQQgBAGgGAKIgCACIAAAFQgBAFgHAJQgtA/gyBSQgfA0g4BjIgnBEQgJAOgGAEQgGAEgNAAIgFAAgAkOFgQgMAMgEAGQgEAHgCAJQgPAygaBmQgZBageA4QAOADAPABQALABAGgCQAHgDAHgNIBmi3QAfg0A6hSQgUAGgYgCQgbgDgZgNQgMgGgHgHQgIAMgKALgAi9DDIgTAGQgKADgGAFQgGAEgIAMIgHAMQgDAHAAAQQAAATADAJQAFANAPAKQALAIASAEIAUAEQAWACASgHIAQgIQANgJAKgPQgEgFABgJIADgOQAGgXgIgOQgDgFgKgIQgPgLgLgDQgMgDgUAAIgTAAgAnKibIg5gfQgQgPgKgFIgOgIQgJgHABgHQAAgEAFgHIAXgiQAUgeARgOQAFgFAFgBQAFgCAIAAIAIABIABAAIAAgBIAQABIAHgYQAGgVAEgKIAGgLIAKgeQACgFgBgDIgDgHQgCgGACgFIACgIIgCgFQgCgEACgIQAEgNAEgFQAFgIAJgDQAFgBAHACIAAgBIAGAEIAGADIADACQADAEADAMIACANIgEAQIgGAPQgGAMgTADQgIAcgHANIgGAMIgQArIAQACQAKACAEAEQADAEgBAKQgDAoAFAVQADALgBAEIgKAKQgDAEgFAIQgFAJgDAEIgIAIQgGAFgBAEIgDALQgDAGgEABIgBAAQgDAAgFgDgAndkwQgDAAgDADQgOANgLAPIgFAJIgWAdQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABIADADQAMAIAGAGIAYAUQAQAMAUAHIAhgwIACgFQABgCgBgGQgFgTADgrIgugFIgIgBIAAAAgAmLncIgCAEIgCAJIACAGIABADIACACIACADIABAEQADgBABgEQADgHAAgKQABgDgCgCQgBgDgFgCIgCAAgACkjJQgCgDgDgJIgKgnQgKgjABgWIAAgHIACgEQACgJAKgIIABgBIgBgBIgVgTQgOgNgGgHIgHgJIgTgTQgDgEgDAAIgHAAQgGgBgDgCQgEgFgCAAIgFABQgDgBgHgFIgKgMIAAgBQgEgHABgIIAVgUIAHgCIAIAAIALAEIALAJIAKAKQAFAKgFASQATARAHAKIAHAKIAdAeIADADIADAEIAZgXQAHgGAFAAQAFABAIAHQAcAcATAJIAIAEIAEAFIABAEIABAKQAAAFAEAJQADAKABAFIABALQAAAIADADIAGAJQADAGgCAFQgCACgGADIg9AWQgWADgKADIgQAHIgGAAQgGAAgEgDgACplCQgGAFAAABIgBAGQABAUAEARIADAKQAFAUADAPQAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQABgBABAAQAOgEAIgBIAegFQAUgEATgKIgQg5IgCgFQgBgCgFgCQgRgIgfgggAA8m1IAGAAIACAAIADAAIADgBIAFAAQAAgCgDgDIgDgDIgJgGIgFgBQgDABgEADIgBABIABAEIACADIAAgBQAEAEACABgAjkj4QgSgDgIgGQgHgGgHgUIgQg0QgNgsgGgZIgIgpQgHgXAIgJQADgDAEAAQADAAAEAEQAHAIAEAUQALA3AjBqQABAFADAEQADACAIACQBeATBagIQAXgCAGgLQABgDABgLIABgVIABgIIADg1IgEgQQgBgEAAgNIAGiIIAAgaQAAgggEgRQgKgrgcgVQgIgGgCgDQgCgDAAgEQAAgDADgCQAFgEAHADQAYAJAPAVQAGAKAHARQAIAVACALQABAKAAAWIAAAOIgCBlIAAAGIACAnIAAAVIAAAEIAAAjQAAAegEAYQgBAJgEANQgCAHgCADIgCACIgDAGQgKAUgnAFQgdAEgiAAQg1AAhCgKgAjwnZQgXAAgOgKQgKgHgJgPQgKgQgCgQIAAgJQggAegeAXIgIgDIgGgEQABgEAFgCQApghAhghQAEgEAEgCIAAgDQACgHAHgKIALgOQAOgNAggEQAdgFAQAHQAJAEAJAHQAQAPAHASQADAIABAIQABAMgDAOQgFAVgQAQIgJAJIACADIgBAAIgFADIgFABIgHAFIgLABIAAACQgSAHgSAAIgFAAgAj1pcQgLADgDACQgFADgJAJIgMAPIABAFIAAAAQABAFgBALQgCAUASAUIAHAGQAEADAGABQALACAJAAQAQAAAPgHQAVgLAJgVQAGgPgDgOQgCgHgDgHIgHgKQgGgHgEgCQgLgIgQAAQgKAAgTAEgAkypWIgEgEIgCAAQgDgDAAgEQAAgGAEgIQAMgWAlgdIAQgLQALgHANgFIAngPIAQgEIACAAIAAgBIAEgOQABgHgBgEIgCgKQgBgGABgEQACgFAFgCQAGgBAEACQAEADADAIQABgFAHABIAJAFQAQAPAQAEQAJACATgBQAVgCAJgIQAHgIACgMQANgxgcg6QgEgJAAgFQAAgEADgDQACgDAEAAQADAAAFADQAFAGAEAHQAaAygHA3QgDAjgTAQQgPALgaADQgSABgOgCQgSgFgLgLIgPgVIgBgBQAFATgIARQgEAIgEADQgHAEgFgDIgHADIg2AcQgUALgYAUIgMAMQgHAHgDAHIgIAMIAAAAIAEAEIgBAAQgBAAAAgBQgBAAgBAAQAAAAgBgBQAAAAAAAAQgEACgEAAIgCAAgAhmqYQgWgCgNgVQgEgJAFgDQAEgDAHAGQAMAKAHACQAMAEAKgEQAHgDABgEIAEgIQAFgFAFAGQADAEgCAHQgCAGgGAGQgMALgRAAIgEAAgAimsBIgFABQgHABgFgBIgMgDQgPgEgFgKQgEgIABgKQACgUAMgJQgEABgFgDQgDgCgCgDIgMgQIgLgTIgEgJIgCgJQAAgKACgKQACgLAEgEQADgEAFgBQAEAAAEACQAFACABAIIgBANIAAAHIABAHIACAGQAIAQAHAIQAFAHABADQAFAJgHAHIgBABQAFgCAGAAQAKABAGAGQAEAEAAAHQgBAIgIACQgIAEAAACQAIABAFAEIAEADQAFAAADACQAEACABAEQACAFgCAEQgBAEgGAEIAAAAIgDAHIgBACQgCgEAAgDgAhOs4QgGgDgBgHQAAgHAGgDIAEgBIABAAQAIAAACAHQADAGgFAFQgEADgEAAIgEAAgAhrtyQgJgBgFgDIgGgDIgHAAQgEAAgCgDQgCgCABgDQABgHAHgCQAFgDAHADIAMAFQAIADARgDQALgCAFgEQAEgDADgGQADgEAAgGQgBgGgFgGQgIgJgQgKQgIgGgGgCIgPgFQgJgEABgIQACgIALgCQAPgCATAJQARAHAKAJQAHAHAJANIAEAJIABALQgBAKgDAGIgDAFIADABIgJAIQgEAEgKAFIAAgBQgSAKgUAAIgMgBgAjHuOIgIgHQgIgGgCgEQgCgDAAgEQABgEACgCQAEgEAHACIAJAFIAKAHQADACADAFQADAFgBAFQAAAEgDACQgDACgDAAQgFAAgHgFgAikubIgHgGQgEgDgIgEIgMgFQgGgDgBgFQgBgGAKgEQAEgBAJABQAJACAGADQAHADADAEQAEAFAAAHQAAAFgDAEQgDADgEAAIgDAAgAh9uvIgFgGQgDgFgIgFQgGgEgLgEQgIgCAAgEQABgEAHgBQAHgBAGAAQAJACALAIQAHAEAEAGQAFAIgEAGQgBAEgDAAIgCAAQgCAAgEgCg");
	this.shape_3.setTransform(117.0443,93.6868);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0000CC").s().p("AEKPLIipgKQgfgCgKgOQgEgHAAgPIgIhcQgBgTAFgHQAJgRAjgBIBogCQAUAAAKACQAMADARALIAtAiQAMAHAGABQAEABAQgCQAkgEAgAQQAVALANASQAOAUABAVQAAAXgOAMQgKAJgYADQgcADgmAAQgiAAgpgDgAC/MtIh7AFQAJAvACAyQAAAHADADQACADAIAAQA7AGAvABIBLAGQBEAGBFgIQAIgBADgEQAEgEgBgFQAAgMgHgLQgPgWgfgHQgXgGghAFQgMABgFgDIgJgJQgEgFgLgHIgsgcQgJgFgEgBQgHgCgNAAIgGAAgAkONuQgMgEgOgUQgfgugjhQIhFiaQgMgdAIgPQAEgGAOgJIBNgvQARgLAJABQASABARAeIAyBbQAKASACALQADAMgBATIgJA4IAAAUIAKAQQAVAfABAjQgBAYgKAVQgLAVgTALQgMAGgLAAQgHAAgHgDgAmOIZQgHADgBAEQgBADADAHQAXA3AUApIAeBHQAaA/AmA5QAGAHAEABQAGACAEgDQAKgFAGgNQANgXgHgeQgGgYgTgaQgIgLABgGIAEgMQACgFADgOIADg0IgBgOQgBgIgJgQIg8hrQgnAegrAZgAC6LxQgegKghABIgSABQgKAAgGgCQgEgBgCgBQgEACgGgDQgJgEACgMIAJgSIANgeIASgzQAQgsAFgXQAFgRAMgzQAJgqAJgYIABgCIgDAAIAEgHQAHgKAGgHIACAAIARgLQAUgLATgOIgBgEIAGAAQgCgIAAgJQgCgSAGgQIAIgPIgBAAIAAgBIABgDIABgBIgBAAQAAgFgCgCIgBgCIgBAAIgDgBIgBAAIgNgOQgDgCgHgLQgLgOgEgHQgHgTgFgIIgIgOIAAAEIgJgPIgJgCIgBgDIgBgEQgEgDgEgIQgag9ghhSIgLgcQgIgPgKgRQgMgSgDgJQgEgLABgSQACgxAKgZQABgFAEgDQAEgEAEACQAFABABAKQABAJgDArQgCAfAIATIASAfQAIANALAdIApBuIABAAQAIAOAKAYIAEAMIAIAKIgBABIAIAKQALAPAFAKIAHANIARAbIAIANIAKAIIAAgBIAAAAIAEAEIACAEIAIgIQAVgQAmADQAPAAAIADIAJAEIACACIABABIABAAIgBgHIAAgCQgJgagHghIgFgDIgGgEIADADIAHADIgHghIgVh1IgGgkQgBgJAAgaQABgWgCgOQgHgYgBgMQgFgXAHgPQADgKAHABQAEAAADAKIALAuQAHAnABAZQgBAaABADQAAAHAHAcIAmDRQADAQgEAKQAAADACACIgBABQAPAOAHAMQALATgFAiQgCAXgIAMQgDAGgJAGIAAABIABAEQgMAEgKAHIgHgBIgTAIIgDABIgDABQgRAegUAuQgjBMgPAmQgPAngaBPQgFAOgHADIgFABQgEAAgHgDgADMGYQgJAFgEAEQgDAEgCAIQgPAogHAqIgKA1QgFAUgOAnIglBhQgCADAAADQAzACAuAQQAih9BDiUIAUgrIgHgBIgEAAQgTgFgLgLIgEgCIgBgBQgDgIAAgIQgGgBgEgGIgHAAIgDgEQgTAPgWAMgAE3EWIgVAFQgIADgEAGQgEADgHALIgFAIIgDAJQgDAZAFANQADAHAHAKIACAEIALABIAOAGQAEABAIABIAOABIAOABIAQgEQAVgIAGgLQAEgIABgQIABgIIgBgGQgBgJgDgGQgDgHgSgPIgPgLIgSgEIgPgCIgCAAgAnOIJIAAAAIAAABgAjAH/QgJAAgOgKQgSgMgXgTQgJgHAAgHIAAgBQgBgIALgIIABAAQAMgKAWgPQAIgEAHgFIABgBQAggUAQgNIAqglIBphgQAUgRAMgEIAZgEQAQgGALAAIAAgFQABgMACgFQABgFAMgSQAJgQAHgFQADgFAIgFIASAZIgCABQgIAFgIANQgKAQgCAJQgDAOAHARQAFANANAMQAEAGAJAIQATAOATAEIASACQAKABALgDIAJAQIgCADQgTAMgTANIgHACIgBABIgHADQg3AXg/AdQg2AahkA1IhGAkQgOAGgHAAIgBAAgAAzDwQgTADgFAEQgIADgHAGQgoAihLBHQhHA9g4AgQAKAJAMAKQAJAGAGACQAIABANgGIC5hiQA2gbBdgkQgUgGgSgPQgVgRgPgZQgHgMgBgJQgOAGgNADgAn1FKIAEgHIgEAIgACtgTQgTgEgUgHIgNgGQgGgEgFgKQgFgHAAgGQgBgGADgKQAPgrALgXQADgGAFgEQABgBAHAAIANABIg2hGIgXgEQgTgDgIgGQgHgGgGgUIgEgMQgGgGgDgHQgFgLABgSQgNgrgFgYIgCgIIgHghQgFgXAHgJQADgDAEAAQADAAAEAEQAGAIAEAUQADAQAGAUIAOA1IAEABIAShZIAEgaIgEAAQgWAAgOgKQgKgHgJgPIgCgCIAAgBIAAAAIgEgIIgCACIAAAAQgEgWABgWQACgFACgEIACgDIADgFIACgGQABgHAHgKIAMgOQAOgNAggEQAdgFAQAHQAJAEAJAHQAQAPAGASQADAIABAIQACAMgEAOQgFAVgPAQIgKAJIgRAMIgFABQgBAAgBAAQgBAAAAAAQgBAAAAABQAAAAAAABIgCABIgBgBIAAABIgOAEIgDANQgFAagFA0QgCAPADAIQgBAIACAEIgCAFQAAAFgCAFIADACQAHAJAAAJQABAHgDAIIgBADIACABIAYAaQBQANBOgHQAXgCAFgLQACgDABgLIABgVQAAgHACgEQADgEAEAAIACAAIABAAQAEACABAIQACALgBAOQgBAQgGAIQgLAUgnAFQg2AIhLgHIALAOIAfApIALAOIgBAAQAJACAIAAIAAABIAAACIADgBIAAAEIAJgBQALACgBAIIgCAJQgCAEABAFIACAIIACAMQAAAKACAEIAEAKQACAFgEAGQgGAQgQASQgGAHgFACQgFADgIAAQgGAAgIgCgACeiJQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBABQgHAOgIAUIgMAdQgCAGABACIAAAHIAGAHQACADAEABIAXAIQANAFAJABQAEAAAEgBQADgBAEgFIAWgcIACgGQACgDgCgFIgGgPQgDgHgGgWIgFgBIgGABQgFAAgCgCIgBgCIgIgDIgEgEIgGAAIgJgBIgCgBIgCAAgAC4iWIABAAIAAgBIgBABgABMkGIABADIAGADIgEgIIgDACgABFkYQADgBACgGIACgDQACgGAAgEIgFgDIgDAAQgEABgEgCIAHAYgABYngQANgBAMgGQAVgLAIgVQAGgPgDgOQgBgHgEgHIgGgKQgGgHgEgCQgMgIgQAAQgJAAgTAEQgMADgDACQgFADgIAJIgMAPIABAFIAAAAQABAFgCALQgBAUARAUIAHAGQAEADAHABIARACIACgTgAHVg/IhAgKQgUgJgLgCIgRgCQgKgDgCgIQgBgDACgJIALgnQAJgkALgSIAEgGIAEgEQAGgGAMgCIACAAIgBgBIgIgcQgGgSgBgJIgCgLIgHgbQgBgEgCgCQgBgBgGgCQgEgEgCgDIgCgHIgFgDQgCgCgDgHQgDgLAAgFIAAAAQAAgJAFgHIAcgGIAIACIAGAEIAIAJIAFANIADAOQAAALgNANQAHAYACANIAAAMIAKAoIACAFIAAAEIAhgHQAJgCAFADQAFADACAJQAKAnANASQABAEADADIABAGIgBAFIgEAIIgEAOIgEAPIgEAKQgEAHABAFIAAALQAAAGgEADIgFABIgEgBgAGZjHQgIABAAABQgCABgCAEQgJARgFARIgCAKQgGAUgGAPQAAABAAAAQgBAAAAABQAAAAAAABQAAAAABABQAAAAAAABQABAAAAAAQABAAAAABQABAAABAAQAOADAHAEIAdALQATAGAWAAIAQg9QAAgDgEgFQgKgQgMgqgAFxlsIAAADIABABIACAGIAFADIADACIACAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABIAEABQABgBgBgEIgBgEIgFgJIgEgEQgDgBgEACIgCAAgAgHhnIABgDIgBADIgBAFIgBABIACgGgAE2lVIgBgKIgFgSQgBgEAAgNIAHiIIAAgaQgBgggEgRQgJgrgcgVQgIgGgCgDQgCgDAAgEQAAgDACgCQAFgEAIADQAYAJAPAVQAHAKAGARQAIAVACALQACAKAAAWIAAAOIgCBlIgBAGIACAnIABAJQAAALgCAIIgGAYIgCAKQgCAGgFAAQgFAAgDgHgAAJonIABgBIgBACIAAgBgAAFpDQgGgDAAgIQgBgGAEgIQAMgWAlgdIAQgLQAKgHANgFIAogPIAPgEIACAAIAAgBIAFgOQABgHgBgEIgDgKQgBgGACgEQACgFAFgCQAFgBAEACQAFADADAIQABgFAGABIAJAFQARAPAQAEQAJACASgBQAWgCAIgIQAHgIADgMQANgxgcg6QgEgJAAgFQAAgEACgDQADgDADAAQAEAAAEADQAFAGAEAHQAcAygHA3QgEAjgUAQQgOALgaADQgTABgOgCQgSgFgKgLIgPgVIgBgBQAEATgIARQgDAIgFADQgGAEgGgDIgGADIg3AcQgTALgZAUIgMAMQgGAHgEAHIgHAMQgFAEgFAAIgDAAgADTqFQgXgCgMgVQgFgJAFgDQAEgDAHAGQAMAKAHACQAMAEALgEQAGgDACgEIADgIQAFgFAFAGQAEAEgCAHQgCAGgGAGQgNALgQAAIgEAAgACTruIgFABQgHABgGgBIgMgDQgOgEgGgKQgDgIABgKQACgUAMgJQgFABgEgDQgDgCgDgDIgMgQIgLgTIgEgJIgBgJQgBgKACgKQACgLAFgEQADgEAEgBQAFAAADACQAFACABAIIAAANIgBAHIABAHIADAGQAHAQAHAIQAGAHABADQAEAJgHAHIAAABQAFgCAGAAQAJABAGAGQAEAEAAAHQgBAIgHACQgIAEgBACQAIABAGAEIAEADQAFAAACACQAEACACAEQABAFgBAEQgCAEgGAEIAAAAIgDAHIAAACQgCgEAAgDgADqslQgGgDgBgHQAAgHAGgDIAFgBIABAAQAHAAADAHQACAGgFAFQgDAEgEAAIgFgBgADNtfQgIgBgFgDIgHgDIgHAAQgEAAgCgDQgCgCABgDQACgHAGgCQAGgDAGADIAMAFQAIADASgDQALgCAEgEQAFgDACgGQADgEAAgGQAAgGgGgGQgHgJgQgKQgIgGgHgCIgPgFQgJgEACgIQABgIALgCQAPgCATAJQASAHAJAJQAIAHAIANIAFAJIAAALQgBAKgDAGIgCAFIACABIgIAIQgFAEgKAFIAAgBQgRAKgUAAIgNgBgAByt7IgJgHQgIgGgCgEQgCgDABgEQAAgEADgCQAEgEAGACIAKAFIAKAHQADACACAFQAEAFgBAFQgBAEgCACQgDACgEAAQgEAAgHgFgACVuIIgIgGQgEgDgHgEIgNgFQgGgDAAgFQgCgGAKgEQAFgBAJABQAIACAGADQAHADADAEQAFAFAAAHQAAAFgEAEQgDADgDAAIgDAAgAC8ucIgFgGQgEgFgIgFQgGgEgLgEQgHgCAAgEQAAgEAHgBQAIgBAGAAQAJACALAIQAGAEAFAGQAEAIgDAGQgCAEgDAAIgBAAQgDAAgDgCg");
	this.shape_4.setTransform(134.5813,95.7758);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0000CC").s().p("ACePXIgrgBIhrgHQgfgCgJgOQgEgHgBgPIgHhcQgCgTAFgHQAJgRAjgBIBngCQAUAAALACQAMADAQALIAuAiQALAHAGABQAFABAPgCQAkgEAgAQQAVALAOASQAOAUAAAVQAAALgDAIIgDACQgbAKgbAGQgqAIhDAAIgmAAgABlM7Ih6AFQAJAvACAyQABAHADADIAAABQABADADADQACACAHAAIANAAIAGAAIAGAAICiAEQAoABAXgCQAWgBAUgEIACAAQANAAAHgEIAKgHIADgCQgBgJgFgIQgQgWgfgHQgXgGggAFQgNABgFgDIgJgJQgDgFgLgHIgtgcQgIgFgFgBQgGgCgOAAIgGAAgAgdMUQgHgEgBgPQgBgTACgoQABgogBgUQgBgSgFglIgSiNQgCgXACgMIACAAIABgFIARg+IAMgWIADgCIgBAAIgBgBIgGgFIgGgFIgBAAIAAgBIgIgRQgBgEAAgVIAAgIIABgQIABgHIAEgLIAAAAIACgEQALgUAOgMIgBAAIhNkZQgFgPAAgKQAAgKAGgQQAJgcAQglIAEgHIABgCIAAAAIABgDIAAAAIACgCIABgBIAEgDIADgBIAEAAIACAAIADACIAAAAIABABIAAAAQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAABIAAAAIABAEIAAAEIAAABIgBABIAAACIgBAAIgBADIAAAAIgBACIgDAFIAAADIgCACQgQAfgDAhIgBAEIgDARIAAgCIgBAMIAAACIABALIABAGQABAIAKAYQALAcAKAyQALA6AHAWIALAgQAFATgBAOIgCAIIAKgHQASgJAfgBQAaAAAVAFIARAIIAHACIABACIAKAMIAHAEIABAAIABgJIAAgOIAAgCIAAgDIAAgFIAAgCIAAgBIABgCIgQhaIgGglQgEgagBggIgGhrQAAgQACgGQADgGAIgGIAOgJIALgJQAHgEAFACQAFABACAFQACAFgBAFQgCAIgKAIIgMALQgDAFABAKIACBKIADA9IAEAjIADAYQAAAvAKAyIACAMIACASIgFAfIAAADIAAACIgBAAQADAMgCAPIgDAXIgEAQIgBADIgDACIgHAIIgGALIgIAIQgGAHgDARQgBAIABAEIgGAcIAAAAQgJAqgHAvQgKA7gQBxIgLBPQgDAQgEAFQgFAHgQAFQgUAIgcAJIgJABQgFAAgDgCgAgFFcIgHAOQgEAJgFAVIgCAFQgCAKgFAJIABAAIgDANQgBAHABAKQAFA0ANBoQAKBcgHA/QANgCAPgEQAKgDAEgEQAGgGACgPIAbjPQAFgkAMgyQABgVAGgVIAJgeIgRACQgaAGgagGQgUgFgOgKIgBADgAA2DFQgXACgLADQgTAGgJALIgIALQgIAJgBAFQgDAHAEAGIgBALQABAUAIAIIABABQAFAOAOAKQALAHASAFIANADIA5gKIAGgDQANgJAJgOQgEgFABgJIAEgPQAFgWgHgOQgEgGgKgIQgJgHgIgDIgCAAIgGgHQgKgHgWAAIgFAAgAl/KQQgJgKgDgYQgGg3AGhWIAKipQACgfAOgKQAHgEAPAAIBcgIQATgBAHAFQARAJABAjIACBoQAAAUgCAKQgDAMgLARIgiAtQgHAMgBAGQgBAEACAQQAEAkgQAgQgLAVgSANQgUAOgVABIgCAAQgWAAgLgOgAlTEmQgHAAgDADQgDACAAAIQgGA7gBAvIgGBLQgGBEAIBFQABAIAEADQAEAEAFgBQAMAAALgHQAWgPAHgfQAGgXgFghQgBgMADgFIAJgJQAFgEAHgLIAcgsQAFgJABgEQACgIAAgSIgFh7QgvAJgyACgAiZGNQgFgDgDgMQgIgfgRgcIgKgOQgFgKgCgGIgBgFQgFgDAAgGQgBgKALgEQAEgCAPgBQALgBAWgEIA0gMIAJgCQAFABACABIACAEQAGAKgHAKIhmAUIgFABQAZAtAKAwQAngMArgKIABABIABACQABAGgDAHIgDAEIAAACIg/APIgKABQgGAAgDgCgAEFF5IgEAAQgTgDgNgKIgEgBIgBgBIgBgCQgDgGgBgHQgGgCgFgEQgPAAgRACIgNABIgCgBIAAgCIACgJQACgHAGgEIAFgEIAOgBQgDgIgBgJQgEgSAFgRIAEgMIADgHIACgFIABgEIADAAIAGgKIABgCQAGgHAJgEIAEgBIAAAAIACgBIAEgDQAPgGAWgBQAPgBAJACIANAGIgCgIIgBgBQgLgagMggIAAAAIAAAAIgLghIgkhxIgJgiIgFgjQgDgXgDgMIgNglQgHgWAEgQQACgKAIAAQAEABAFAJIAQAsQAMAmADAZIAEAeIALAjIA+DJQAGAQgCAKIABAGIAAABQARALAIALIAFAIQAIASAAAbQAAAXgGAMQgEAHgGAHIAAABIAAADIgQAKIgFAEIgGAAIgSAKIgDAAQgIADgLAAIgTAAgAD3DlIgUAHQgHAEgEAFIgEAHIgFAIIgEAJIgBAJQgBAZAGANQAEAHAHAIIAEAEIALABIAOAEIANABIAOAAIAOgCQAHgBAIgEQATgKAFgLQAEgJgBgQIAAgIIgCgGQgCgJgDgGIgHgHIgRgMQgNgIgDgBQgGgCgNgBIgJAAIgIABgAEshFQgJgCgGgDQgFgEgGgKQgbgqgMgbQgEgHABgFQAAgCAGgHQAQgPATgKQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIgMgHIhgg6IgVgLIgJgIIgFAGQgHACgJAAQgXgBgMgNQgJgIgDgSQgBgMAEgIIgDgCIgFgGIgPgdIgGgKIgGgIIgDgIIgFgIIgDgIQgDgKgKgPIgOgWQgQAFgRgBQgXAAgOgKQgKgHgJgPIgGgLIgBACIgHgiIgCgCIAGgIQABgFADgEIACgDIADgFIABgGQACgHAHgKIALgOQAOgNAggEQAcgFAQAHQAJAEAJAHQAQAPAHASQADAIABAIQABAMgDAOQgFAVgQAQIgJAJIgOAKIACAEQAIALAQAcIAlBEQAEAIAAAFIAFAAIAAgEIAlAGIgBAKIAEABQAKAEACAKQADAGgCAIQAAABAAAAQAAABAAAAQAAABAAAAQAAABABABQAAgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQAZAKAiAUIACABIAQAKIAqAcQAVALAMAJIAGgJQAKgIAHAHIAGAIQACAFAGACIAIAEIAMAIQAIAGAGABIAMAFQAFACADAHQAJAQADAaQACALgBAFQgDALgSALQgTANgXAMIgPAEQgDABgFAAQgGAAgHgBgAEdi4IgHAAQgCABgEAEIgHAGIgEACQAAABAAAAQAAABAAAAQAAABAAABQAAAAABABQAGAQAMAUIARAfIAFAHIAIAEQAHACADgBQADAAAEgDIAagMQAPgFAHgJIAHgGQABgDgCgHIgHgmIgFgHQAAgDgGgCQAAgBgSgEQgJgDgXgLIgGADQAAADgDACQgEAEgFABIgBAAIgJAEgABkk0QACACAIADQAFADADgBQAEgCAAgHIABgDQABgIgBgCIgGgCIgEACQgFAEgIgCIgHgDQACALAFAFgAgrpSQgLADgDACQgFADgJAJIgMAPIABAFIAAAAQABAFgBALQgCAUASAUIAHAGQAEADAGABQALACAJAAQAQAAAOgHQAVgLAJgVQAGgPgDgOQgCgHgDgHIgHgKQgGgHgEgCQgLgIgPAAQgKAAgTAEgAgajuQgSgDgIgGQgHgGgHgUIgQg0QgNgsgGgZIgIgpQgHgXAIgJQADgDAEAAQADAAAEAEQAHAIAEAUQALA3AjBqQABAFADAEQADACAIACQBXASBVgGQACACAHACQAJAEgDAHQgBADgEACIgFAAQgdAEgiAAQg1AAhBgKgADBkfIAAgPQAAggACgfIAAgDIgCgKQgBgEAAgNIAGiIIAAgaQAAgggEgRQgKgrgcgVQgIgGgCgDQgCgDAAgEQAAgDADgCQAFgEAHADQAYAJAPAVQAHAKAHARQAIAVACALQABAKAAAWIAAAOIgCBlIAAAGIACAnQABARgDALIgFAYIgCAKIgBACIACArIgBALIgCAFIAAAFIgGABIgBAAQgFAAgHgFgAhmowIABgBIgBACIAAgBgAhppMQgIgDAAgIQAAgGAEgIQAMgWAlgdIAQgLQALgHANgFIAmgPIAQgEIACAAIAAgBIAEgOQABgHgBgEIgCgKQgBgGABgEQACgFAFgCQAGgBAEACQAEADADAIQABgFAHABIAJAFQAQAPAQAEQAJACATgBQAVgCAJgIQAHgIACgMQANgxgcg6QgEgJAAgFQAAgEADgDQACgDAEAAQADAAAFADQAFAGAEAHQAbAygHA3QgDAjgUAQQgPALgaADQgSABgOgCQgSgFgLgLIgPgVIgBgBQAFATgIARQgEAIgEADQgHAEgFgDIgHADIg1AcQgUALgYAUIgMAMQgHAHgDAHIgIAMQgEAEgFAAIgDAAgABjqOQgWgCgNgVQgEgJAFgDQAEgDAHAGQAMAKAHACQAMAEAKgEQAHgDABgEIAEgIQAFgFAFAGQADAEgCAHQgCAGgGAGQgMALgRAAIgEAAgAAjr3IgFABQgHABgFgBIgMgDQgOgEgFgKQgEgIABgKQACgUAMgJQgEABgFgDQgDgCgCgDIgMgQIgLgTIgEgJIgCgJQAAgKACgKQACgLAEgEQADgEAFgBQAEAAAEACQAFACABAIIgBANIAAAHIABAHIACAGQAIAQAGAIQAFAHABADQAFAJgHAHIgBABQAFgCAGAAQAKABAGAGQAEAEAAAHQgBAIgIACQgIAEAAACQAIABAFAEIAEADQAFAAADACQAEACABAEQACAFgCAEQgBAEgGAEIAAAAIgDAHIgBACQgCgEAAgDgAB7suQgGgDgBgHQAAgHAGgDIAEgBIABAAQAIAAACAHQADAGgFAFQgEADgEAAIgEAAgABetoQgJgBgFgDIgGgDIgHAAQgEAAgCgDQgCgCABgDQABgHAHgCQAFgDAHADIAMAFQAIADARgDQALgCAFgEQAEgDADgGQADgEAAgGQgBgGgFgGQgIgJgQgKQgIgGgGgCIgPgFQgJgEABgIQACgIALgCQAPgCATAJQARAHAKAJQAHAHAJANIAEAJIABALQgBAKgDAGIgDAFIADABIgJAIQgEAEgKAFIAAgBQgSAKgUAAIgMgBgAACuEIgHgHQgIgGgCgEQgCgDAAgEQABgEACgCQAEgEAHACIAIAFIAKAHQADACADAFQADAFgBAFQAAAEgDACQgDACgDAAQgFAAgHgFgAAluRIgHgGQgEgDgIgEIgMgFQgGgDAAgFQgBgGAJgEQAEgBAJABQAJACAGADQAHADADAEQAEAFAAAHQAAAFgDAEQgDADgEAAIgDAAgABMulIgFgGQgDgFgIgFQgGgEgLgEQgIgCAAgEQABgEAHgBQAHgBAGAAQAJACALAIQAHAEAEAGQAFAIgEAGQgBAEgDAAIgCAAQgCAAgEgCg");
	this.shape_5.setTransform(143.4881,94.239);

	this.instance_1 = new lib.CachedBmp_9();
	this.instance_1.setTransform(128.9,-7.9,0.0491,0.0491);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0000CC").s().p("Aj4PSQgtAAgfgJQgegJgsgdQg0ghgVgJQgSgJgEgFQgLgPAKgdQANgmAUgkQgEgCgCgFQgCgFADgEQAEgJAMgBQAGgBANAEIAmAOQAXAIARABQAVAAAFACQAJADAIAKQAIAIAIAPIAPAZQAGALALAOQAGAHAGADQAGAEAQgBQA6gCAdATQAUANAFASQADAPgIAQQgHAPgPAJQgVANgpADIghABIgKAAgAm9L7IgCAEQgPAlgMAhQgGAOAFAHQACACAIAEQApASAjAXQAkAYAMAFQASAHAmAEIAoADQATAAAvgGQASgEAFgCQANgIAAgKQABgLgJgIQgIgGgLgCQgYgHgoACIgOABQgIgBgGgCQgIgEgKgKIgXgcIgNgWQgHgPgGgIQgGgHgFgDQgGgBgGABQgTAAgZgIIgqgQIgEAAIgDAAgAClO4QgHgEgIgNIgwhOQgKgQABgJQAAgTAfgRIBbgyQARgKALgCQAMgDAUACIA4AJQANABAGgCQAEgBANgJQAegVAkAAQAYAAAUAKQAWALAKATQALAVgHAQQgFANgUAOQgtAehQAjIibBFQgRAIgMAAQgIAAgGgEgAD4L7QgIACgQAIIhsA9QAeAnAZAqQAEAHAEABQADABAHgDQA3gXAqgTIBFgeQA/gaA6gnQAHgFABgEQABgGgDgFQgFgKgMgGQgYgNgeAIQgYAGgaATQgKAHgGAAIgNgFQgEgCgOgCIg0gEIgOABgABSL6QgCgEgCgPQgCgLgHgVIgSgyQgQgtgJgVIgdg/QgSgmgJgZQgFgLAAgJQAAgJAJgUQALgZAGgeIgFgFQgFgHAAgIQgLgDgJgNQgLgOgDgSQgDgSAEgRIAHgTQAHgOAGgHQAUgVAqgCQAOgBAJACIAOAGIgDgIIAAgBQgSgngRg0IgihxIgKgiIgFgjQgCgXgEgMIgNglQgGgWAEgQQACgKAHAAQAFABAEAJIAQAsQALAmAEAZIADAeIALAjIA/DJQAFAQgCAKIACAGIAAABQARALAIALQANATAAAiQAAAXgHAMQgDAHgHAHIAAABQAGAlAQA/QAUBQAMAnQANAoAeBOQAEAOgDAGQgDAEgLAFQgeALgaAVIgNALQgJAGgGADIgFABQgCAFgGACIgDAAQgIAAgFgJgAgHGwQgEAJAAAFQAAAFADAIQANAoAUAlIAaAvQAIATANAnIAhBjIABAFQAqgeAvgPQg0h3gpicQgKgkgEgbQgMAHgMADQgIADgLAAIgUAAIgPgBQgHAcgKAegAALDjIgSAHQgIAEgDAFIgJAPIgFAJIgBAJQgBAZAHANQADAHAIAIIAEAEIAKABIAOAEIAMABIAOAAIAOgCQAHgBAJgEQATgKAFgLQAEgJgBgQIgBgIIgBgGQgCgJgEgGQgEgGgTgNQgNgIgEgBQgGgCgNgBIgIAAIgJABgAlzLaQgWAAgegDQgLgBgFgGQgFgHAFgOQAHgSAQglQAQgkAGgTQAGgRAJgkIAkiKQAHgbAIgJIASgRQAMgPAIgGIgCgDIgIgRQgBgEAAgVQgBgSACgJQABgHAGgMQALgUAOgMIgBAAIhNkZQgFgPAAgKQAAgKAGgQQAJgcAQglQAHgPAJACQAJADgCAQQgCAMgGASIgLAeQgMAlAGAZQABAIAKAYQALAcAKAyQALA6AHAWIALAgQAFATgBAOIgCAIIALgHQASgJAfgBQAxgBAcAUIANAKIAJAKIgXiGIgGglQgEgagBggIgGhrQAAgQACgGQADgGAIgGIAOgJIALgJQAHgEAFACQAFABACAFQACAFgBAFQgCAIgKAIIgMALQgDAFABAKIACBKIADA9IAEAjIATCrQAAAKgDACQgCADgDABQADAMgCAPIgDAXIgEAQQgCAFgGAKIgBADIgBAFQgBAFgGAIQgtA/gyBTQgfAzg5BjIgnBFQgIAOgGADQgGAFgNAAIgFgBgAkkFuQgNANgDAGQgEAGgDAKQgPAygZBlQgZBageA4QAOADAPACQALABAFgCQAIgEAHgNIBmi2QAeg1A7hSQgVAGgXgCQgbgCgagOQgLgGgIgHQgHANgKAKgAjUDSIgTAFQgKAEgFAEQgGAEgIAMIgIAMQgDAIAAAPQAAATAEAJQAFAOAPAKQALAHASAFIATAEQAWABATgHIAQgIQANgJAJgOQgEgFABgJIAEgPQAFgWgHgOQgEgGgKgIQgOgKgLgDQgMgEgUAAIgUABgAmUhaIg7gbQgRgNgKgFIgQgHQgJgGAAgHQAAgEAFgIIAUgjQASggAQgPQAFgFAEgCQAIgDANABIABAAIAAgCIgBgdQgBgSABgKIABgLIAAgbIAAgCIgBgFQgBgBgFgEQgDgEAAgEIgBgHIgEgEQgCgDgBgHQAAgMABgFQADgJAHgFQAEgCAHgBQABgDADgEQAWgmAPgjQACgGADgCQAFgEAEAEQADADgDAIQgUAsgUAjIACABQAFACAHAJIAFAKQABADAAALIAAAPQgCALgRAIIAAABQABAZgCAMIgCAMIgBAqIAAAJIAhABQAKABADAEQAEAEAAAKQAAAoAHAUQADALgBAEQAAACgIAJIgHANIgIANIgHAJQgFAFgBAFIgCAKQgCAHgFABIgCAAIgHgCgAmzjuQgCABgDADQgNAOgJAQIgFAJQgKASgKANQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABIADADQAMAGAHAGIAZASQARALAVAGIAdgzIACgFQAAgCgCgGQgGgSAAgsIgugBIgIgBIgBAAgAmnmXIAAAEIABAHIAEAEIACADIACABIADACIADACQABgBAAgEQABgGgDgIIgCgEQgDgCgFAAIgBAAgABSjMQgGgBgJgGQgmgZgUgQQgFgFgCgEIAAgKQAGgTAKgPIgCgBIgMgCIhhgKIgTgBIgLgCIgCAGQgDAFgIADQgRAIgOgFQgLgEgKgOQgHgKABgJQAAgGAEgEQADgDADgBIgghAIgMgVIgRgaIgCAAQgUAIgWgBQgXAAgOgKQgKgGgJgPQgKgQgCgRQgCgSAIgMIACgDIADgFIABgGQACgHAHgJIALgPQAOgMAggEQAdgFAQAGQAJAEAJAIQAQAOAHASQADAIABAIQABANgDANQgFAWgQAQIgJAJIADAFIAQAWQAGAIAKATIAeA6IAEAIIADAAQAGAAAFADIAEADQAFAFACAIIACADIACgBQAZgBAjADIA7AHQAUACAMADQAAgGACgDQAEgLAIADIAIAFQADACAFAAIAIAAIANACQAJACAEgBIALgCQAFAAAGAFQANAKANAUQAGAIABAFQADAKgJAQQgIASgMASIgJAKQgFAFgLADQgHACgFAAIgCAAgABPlBQgIABgXAAIgCAFQABADgBADQgCAFgDACIgBAAQgDAGgCABIgFADQgBACgBAFIgDAHQgBABAAAAQAAABAAAAQgBAAAAABQAAAAAAABQAAAAAAABQABAAAAABQAAAAAAAAQABABAAAAQAMALASAMIAZATQAFADACABIAIAAIAIgDIAFgGIANgTQAIgMADgJQACgDAAgFQgBgDgEgFIgVgcIgGgEQgCgCgFAAIgQADgAiblEIAJABQAEAAACgCQADgDgDgGIgBgEQgCgGgDgCIgFAAIgBAEQgDAFgGACQgEABgDgBQAGAJAHACgAkmpOQgLAEgDACQgFACgJAKIgMAPIABAEIAAABQABAFgBALQgCATASAUIAHAHQAEACAGABQALADAJAAQAQAAAPgIQAVgKAJgVQAGgPgDgPQgCgHgDgHIgHgJQgGgHgEgDQgLgIgQAAQgKAAgTAEgAkVjpQgSgDgIgHQgHgGgHgTIgQg1IgKgkIgJggIgIgpQgHgYAIgIQADgEAEABQADAAAEAEQAHAHAEAVQAGAeANAuIAbBVQABAEADAEQADADAIACQBeASBagIQAXgCAGgKQABgDABgLIABgVQAAgIACgDQAEgGAGABQAEACABAJQACAKgBAPQgBAPgFAJQgLAUgnAFQgdAEghAAQg1AAhDgKgAgzlZIgCgKIAAgCIgEgRQgBgDAAgOIAGiIIAAgaQAAgfgEgSQgKgrgcgVQgIgFgCgEQgCgDAAgDQAAgEADgCQAFgDAHADQAYAIAPAWQAHAKAHAQQAIAVACALQABALAAAVIAAAOIgCBmIAAAGIACAnQABARgDALIgEAVIgBADIgCAJQgCAGgGAAQgEAAgDgGgAlkpIQgIgCAAgJQAAgFAEgJQAMgWAlgcIAQgMQALgGANgGIAngPIAQgEIACAAIAAAAIAEgPQABgHgBgDIgCgLQgBgGABgEQACgEAFgCQAGgCAEADQAEADADAHQABgFAHABIAJAGQAQAOAQAEQAJACATgBQAVgCAJgIQAHgHACgMQANgxgcg6QgEgJAAgFQAAgEADgDQACgEAEAAQADAAAFAEQAFAFAEAIQAbAxgHA3QgDAkgUAQQgPALgaACQgSACgOgDQgSgEgLgLIgPgVIgBgBQAFASgIASQgEAHgEADQgHAEgFgDIgHAEIg2AbQgUALgYAVIgMALQgHAHgDAIIgIALQgEAFgFAAIgDgBgAiXqJQgWgDgNgUQgEgJAFgDQAEgDAHAGQAMAKAHACQAMAEAKgFQAHgDABgDIAEgJQAFgEAFAGQADADgCAHQgCAHgGAGQgMALgRAAIgEAAgAjXryIgFAAQgHACgFgCIgMgCQgPgFgFgKQgEgHABgLQACgUAMgJQgEABgFgDQgDgBgCgEIgMgPIgLgTIgEgKIgCgIQAAgLACgKQACgKAEgFQADgDAFgBQAEgBAEACQAFADABAIIgBANIAAAHIABAGIACAHQAIAPAHAJQAFAHABADQAFAJgHAHIgBABQAFgDAGABQAKAAAGAHQAEAEAAAGQgBAIgIADQgIADAAACQAIACAFADIAEAEQAFAAADABQAEADABAEQACAEgCAEQgBAFgGADIAAABIgDAHIgBACQgCgEAAgDgAh/sqQgGgCgBgIQAAgGAGgEIAEgBIABAAQAIAAACAHQADAHgFAFQgEADgEAAIgEgBgAictjQgJgBgFgDIgGgDIgHgBQgEAAgCgCQgCgCABgEQABgGAHgDQAFgCAHACIAMAFQAIADARgDQALgCAFgDQAEgDADgGQADgFAAgFQgBgHgFgGQgIgIgQgLQgIgGgGgCIgPgFQgJgEABgIQACgHALgCQAPgCATAJQARAHAKAJQAHAGAJANIAEAKIABALQgBAKgDAGIgDAEIADABIgJAIQgEAEgKAGIAAgBQgRAKgVAAIgMgBgAj4t/IgIgHQgIgGgCgFQgCgDAAgEQABgEACgCQAEgDAHACIAJAFIAKAGQADADADAFQADAFgBAFQAAADgDACQgDADgDAAQgFAAgHgFgAjVuNIgHgFQgEgEgIgDIgMgGQgGgDgBgEQgBgHAKgDQAEgBAJABQAJABAGAEQAHADADADQAEAGAAAGQAAAFgDAFQgDADgEAAIgDgBgAiuugIgFgGQgDgFgIgGQgGgEgLgDQgIgCAAgEQABgEAHgBQAHgCAGABQAJABALAIQAHAEAEAGQAFAIgEAHQgBADgDABIgCAAQgCAAgEgCg");
	this.shape_6.setTransform(191.7243,94.4631);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0000CC").s().p("ADlO8IiogSQgfgEgJgOQgDgIAAgPIgDhbQgBgTAFgIQAKgPAjAAIBnACQAVAAAKAEQAMAEAQALIAsAjQALAIAGACQAFABAPgCQAkgDAgASQAUAMANATQANAUgBAWQAAAXgPALQgKAIgYADIggABQgvAAg/gHgAAtN7QAAAHADADQACADAHABQA8AIAuADIBLAJQBDAKBGgGQAIgBADgDQAFgEgBgFQABgLgIgMQgOgXgegJQgXgGggADQgNABgFgDIgJgKQgDgEgLgJIgrgdIgNgHQgHgCgSgBIh7gBQAGAxAAAxgAjNPBQgMgBgTgPQgqglg2hEIhqiDQgUgZAEgQQADgIALgLIA+hDQANgOAJgBQASgEAYAYIBIBLQAPAPAEAKQAGALAEASIAGA5QACANADAGQADAEALAJQAcAYAKAjQAGAWgFAXQgFAYgQAPQgOAOgQAAIgFgBgAmhKYQgFAFAAAEQAAAEAEAFQAlAwAeAjIAvA8QApA2A0AtQAHAFAEAAQAHABADgEQAIgIADgNQAGgbgOgbQgMgVgZgUQgLgJgBgGIABgNQABgFgBgOIgKgzIgFgOQgDgHgNgNIhWhYQgeAngjAjgADcLDQgfgIghADIgRABQgKAAgIgBIgEgCQgFADgGgCQgJgEABgMQABgEAGgOQAFgKAGgVIAOg0QAMguAEgXQAEgQAHg0QAGglAGgYIgBAAIgDACIgDAEQgDAEgLAEIggAQIgCAAIgGADQg1Abg8AhQg1AchiA7IhEAnQgPAIgHAAQgIAAgPgJQgSgKgYgSQgKgHgBgHIAAgBQgBgHALgJIABgBIAhgaIANgKIABgBQAggWAPgOIAngnIBkhlQAUgUALgEIAZgFQAQgHAKgBQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQABgMACgFQABgFAKgSQAIgRAHgGQAEgGAMgHQATgLASgEIgBgBIABgFIACAAQgJgRgIgcIgRgzQgUg3g1hEQgLgPgBgFQgCgFAAgVIgCgdQgBgjAOgiQADgHAFgCQAEgBAEAFQADAEABAFQABALgDASQgDAVAAAIIADAbIAAAOIABANQABAGAIAQQAXAhAVAnQAMAUAGARIANApIAUBHIABAJIAHgBQAVACAaAPQAsAXAOAfIAFAOIABgJQACgeACgPIAJguIgCABIAAgDIACAAIAAgBQACgMABgmIAEhHIADgvQAGhDAEgaQABgGACgCQAEgFAEACQADACABAGQADAPgCAZIgHCxQgCAvgFAXIgHAlQgCAPgBAeIgCANIgCADQgEAFgBAKQgBANgBADIgFAMIgEALIgMAIIgBABQgJAEgDAFQgDAEgCAIQgLAqgEAqIgGA1QgDAUgLAoIgeBkIgBAFQAzgCAwAPQAYiAA2iYIAOgjIAKgYIAFAAIgNgBIgSgHIAAgBIgFgGQgEgHgBgIQgKgCgKgNQgKgOgDgSQgEgSAFgRIAHgTQAGgOAHgHQATgWArgCQAPgBAJADIANAFIgCgHIgBgCQgRgmgRg0IgkhxIgJgjIgFgjQgDgWgDgNIgNglQgHgWAEgPQACgKAIAAQAEAAAFAJIAQAtQAMAmADAYIAEAfIALAiIA+DKQAGAPgCALIABAGIAAAAQARALAIALQANATAAAjQAAAWgGANIgEAGQgFACgFAGIgGAJIgEADIgKAGIAAAAIgFADQgUAJgZABIAGACIgRAkIgVA2QgcBOgMAnQgMAogUBRQgEAOgGADQgCABgFAAIgKgBgAgSFJQgRAEgGAEQgHAEgHAGQgmAkhIBMQhDBAg2AjIAXASQAJAGAGABQAHABAOgHICzhsQA0geBbgqQgUgFgUgNQgWgQgPgYQgIgMgCgJQgMAHgOAEgABdDkQgIAAgMAHIgNAGQgHAGgIANQgJAQgCAKQgCAOAIAQQAGANAOAMQAEAFAKAIQATAMATAEIASABQAQgBAPgIQgBgHAGgHIAKgLQAQgQAAgQQAAgHgFgMQgHgQgIgIQgJgJgRgLIgRgJIgTgEIgNgCIgEABgAFFDTIgUAHQgHAFgEAFIgJAPIgEAIIgBAJQgBAaAGAMQAEAHAHAJIAEAEIALAAIAOAEIANABIAOAAIAOgBQAHgCAIgEQATgKAFgLQAEgIgBgQIAAgJIgCgGQgCgJgDgFQgEgHgUgMQgNgIgDgBQgGgCgNgBIgIgBIgJABgAB1geQgIglgDgXQAAgIABgEIAIgHQARgJASgEIgBgBQgBgDgGgIIgSgWQgFgLgPgPIgEgEIgUgYIAAgBIgygGQgTgDgIgHIgDgDIgBgHQgEgJgEgFIAAgBIgQg1QgOgsgFgYIgJgpQgGgYAIgIQADgEAEABQADAAAEAEQAGAHAEAVQALA0AfBiIABgNQACgNAHgFQAFgEAFAAIAEABIgBgFIgDgSIgEgkIgBgbIgDgWIgFgYIgBgKIgEAAQgVAAgOgKQgKgGgJgPQgLgQgCgRQgBgSAHgMIACgDIADgFIACgGQABgHAHgJIAMgPQAOgMAfgEQAdgFAQAGQAJAEAJAIQAQAOAGASQADAIABAIQACANgEANQgFAWgPAQIgKAJIABABIgLAHIgMAIIgBgCIgDAAIgQAFIAEAXIADAUIABAXQgBAOABAGIACAPIACAVIACAUIACAKIgBAEIAMAMIADABQAEAGgBAGQABAGgFAIIgBADIADABIALALQBDAIBCgGQALgBAHgCQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAFgFQADgEACgIIAEgSIAAgBQADgUABgKIgCgaIgBgbIgCAAIgBgPIAHiIIAAgaQgBgfgEgSQgJgrgcgVQgIgFgCgEQgCgDAAgDQAAgEACgCQAFgDAIADQAYAIAPAWQAHAKAGAQQAIAVACALQACALAAAVIAAAOIgCBmIgBAGIACAnQABARgCALIAAABIgCAAIACARQACAbgBAQQgBAYgHASIgFANIgFAKQgLAUgnAFQgQACgSABQgDgCgFAAIgLAAIgKgBIgHAEIgIACIACgCIgagBIAFAGIAlAvIAUAaIAIgFQAKgEAEAHIACAJQABAEAEADIAGAGIAHALQAFAHAEACIAJAHQADADABAIQABAMgCAQIgBALIAAABIgDAEIgCACIgEAOQgGAFgNAEQgSAFgVAEIgKABgACPhlIgHADIgEACQAAAAAAABQgBAAAAAAQAAABAAABQAAAAAAABQABAQAEAUIAEAgIACAIIAGAFIAHAEIAIgBIAXgEQAOgCAJgFQADgBADgDQACgDABgGIAEgjIAAgHQgBgDgDgDIgNgKQgHgEgQgRIgFACIgFAFQgEACgEgBIgBAAQgGABgCgBIgGAAIgGACgAAokCIAGAHQADADADAAQAEAAACgGIACgEQADgGgBgDIgDgEQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgFACgGgDQgDgCgCgDQgCALADAGgAANo+QgMAEgCACQgFACgIAKIgMAPIABAEIAAABQABAFgCALQgBATARAUIAHAHQADACAHABQALADAIAAQARAAAPgIQAVgKAIgVQAGgPgDgPQgBgHgEgHIgGgJQgGgHgEgDQgMgIgQAAQgJAAgTAEgAHBkUIAAgDIgCgFIABABQAGAIABAFIABAGIgHgMgAgxo4QgHgCAAgJQgBgFAFgJQAMgWAlgcIAPgMQAKgGANgGIAogPIAPgEIACAAIAAAAIAFgPQABgHgBgDIgDgLQgBgGACgEQACgEAFgCQAFgCAEADQAFADADAHQABgFAGABIAJAGQARAOAQAEQAJACASgBQAWgCAIgIQAHgHADgMQANgxgcg6QgEgJAAgFQAAgEACgDQADgEADAAQAEAAAEAEQAFAFAEAIQAcAxgHA3QgEAkgUAQQgOALgaACQgTACgOgDQgSgEgKgLIgPgVIgBgBQAEASgIASQgDAHgFADQgGAEgGgDIgGAEIg3AbQgTALgYAVIgMALQgGAHgEAIIgHALQgFAFgFAAIgDgBgACcp5QgXgDgMgUQgFgJAFgDQAEgDAHAGQAMAKAHACQAMAEALgFQAGgDACgDIADgJQAFgEAFAGQAEADgCAHQgCAHgGAGQgNALgQAAIgEAAgABcriIgFAAQgHACgGgCIgMgCQgOgFgGgKQgDgHABgLQACgUAMgJQgFABgEgDQgDgBgDgEIgMgPIgLgTIgEgKIgBgIQgBgLACgKQACgKAFgFQADgDAEgBQAFgBADACQAFADABAIIAAANIgBAHIABAGIADAHQAHAPAHAJQAGAHABADQAEAJgHAHIAAABQAFgDAGABQAJAAAGAHQAEAEAAAGQgBAIgHADQgIADgBACQAIACAGADIAEAEQAFAAACABQAEADACAEQABAEgBAEQgCAFgGADIAAABIgDAHIAAACQgCgEAAgDgACzsaQgGgCgBgIQAAgGAGgEIAFgBIABAAQAHAAADAHQACAHgFAFQgDADgEAAIgFgBgACWtTQgIgBgFgDIgHgDIgHgBQgEAAgCgCQgCgCABgEQACgGAGgDQAGgCAGACIAMAFQAIADASgDQALgCAEgDQAFgDACgGQADgFAAgFQAAgHgGgGQgHgIgQgLQgIgGgHgCIgPgFQgJgEACgIQABgHALgCQAPgCATAJQASAHAJAJQAIAGAIANIAFAKIAAALQgBAKgDAGIgCAEIACABIgIAIQgFAEgKAGIAAgBQgRAKgUAAIgNgBgAA7tvIgJgHQgIgGgCgFQgCgDABgEQAAgEADgCQAEgDAGACIAKAFIAKAGQADADACAFQAEAFgBAFQgBADgCACQgDADgEAAQgEAAgHgFgABet9IgIgFQgEgEgHgDIgNgGQgGgDAAgEQgCgHAKgDQAFgBAJABQAIABAGAEQAHADADADQAFAGAAAGQAAAFgEAFQgDADgDAAIgDgBgACFuQIgFgGQgEgFgIgGQgGgEgLgDQgHgCAAgEQAAgEAHgBQAIgCAGABQAJABALAIQAGAEAFAGQAEAIgDAHQgCADgDABIgBAAQgCAAgEgCg");
	this.shape_7.setTransform(205.3234,96.2789);

	this.instance_2 = new lib.CachedBmp_8();
	this.instance_2.setTransform(196.05,-9.3,0.0491,0.0491);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0000CC").s().p("AjpPhQgzgDgXgUQgIgGgKgNIgQgVQgQgTgjgTQgzgbgHgFQgRgLgDgNQgDgKAHgRQANgiATglQAHgPAJgEQAJgEATAGQAhAKAhACQAbABAIAFQAJAFAIANIALAXQAEAJANAUQAMASAFALIAHAOQAEAHAFAEQAIAFAPABQAmACAYAKQAiAOAOAaQAIAMAAANQAAAPgIAJQgJAKgXAEQguAJgzAAIgaAAgAmfLoQgDACgDAGQgRAjgNAhQgCAIABACQABAEAGAEQAMAHArAVQAiAQASAPQAQAOAOAUQANARAFAEQAHAEAOADQBBANBfgPQAJgDABgBQAGgHgHgMQgMgVgcgJQgQgGgigDQgZgCgMgHQgHgGgHgLIgKgVQgEgJgPgUQgMgTgFgLIgFgNQgEgHgEgEQgIgGgWAAQgmAAghgNQgGgDgEAAIgEABgADWOqQgHgFgIgNIgwhOQgKgQABgJQAAgSAfgRIBbgyQARgKALgCQAMgDAUACIA4AIQANABAGgBQAEgCANgIQAegVAkAAQAYAAAUAKQAWALAKATQALAUgHARQgFAMgUAOQgtAfhQAjIibBEQgRAIgMAAQgIAAgGgDgAEpLtQgIABgQAJIhsA8QAeAnAZArQAEAGAEABQADACAHgDQA3gXAqgUIBFgeQA/gZA6goQAHgFABgEQABgGgDgEQgFgKgMgGQgYgNgeAHQgYAGgaATQgKAIgGgBIgNgEQgEgCgOgCIg0gEIgOABgABqLrQgCgDgCgPQgCgLgHgVIgSgyQgQgtgJgWIgeg+QgSgngIgYQgFgMAAgJQAAgJAJgUQAKgZAGgdIgFgGQgFgHAAgIQgKgCgJgNQgLgOgDgSQgDgSAEgRIAHgTIAGgKIgBgBIgDgCIgBgDIgBgCIABgBQgJgMgJgLIghgfQhXhOgpg8IgYgkIgng9QgMgTgFgMIAAgCQgGgMAAgJQAAgLAGgTQAJgjARggQACgGACgBQAEgBADACQADACABAEQACAFgDAJQgJAagHAjQgCAOABAJIABAEQACAFAEAGQBFBtAtAyQATAWAeAdIAzAyQAdAdANAYIAHgEQAHgBAEgDQAFgDAEgDIABAAIAAAEIATgCQAOgBAJADIAOAFIgDgHIAAgCQgSgmgRg0IgjhxIgKgjIgFgjQgCgWgDgNIgNglQgGgWAEgPQACgKAHAAQAFAAADAJIAQAtQAMAmAEAYIADAfIALAiIA/DKQAFAPgCALIACAGIAAAAQARALAIALQANATAAAjQAAAWgHANQgDAGgHAHIAAABQAGAmAQA/QAUBQAMAnQANAoAeBOQAEAOgDAFQgDAFgLAEQgeAMgaAUIgNALQgJAGgGADIgFACQgCAFgGABIgDAAQgIAAgFgJgAAQGhQgEAJAAAFQAAAFADAIQAOApAUAlIAaAvQAIATANAnIAhBjIABAFQAqgfAvgPQg0h2gpidQgKgkgEgaQgMAHgMADQgIACgLABIgUAAIgPgBQgHAcgLAdgAALDaQgLAHgDAKQgCAGABAFIgEAGIgBAJQgBAaAHAMQADAHAHAJIAEAEIAKAAIAPAEIAMABIAOAAIAOgBQAHgCAJgEQATgKAFgLQAEgIgBgQIgBgJIgBgGQgCgJgEgFQgEgHgTgMQgNgIgEgBQgGgCgNgBQgLgBgGABIgDACIgGgBQgIAAgHAFgAldLMQgVAAgegEQgMgBgEgFQgFgHAFgOQAGgTAQgkQAQgkAHgTQAGgSAJgkIAjiKQAIgaAIgKIASgRQALgOAIgGIgCgEIgHgQQgBgEAAgWQgBgSACgJQABgHAGgMQALgTAOgMIgBgBIgBgCIAIgEQgDgKgBgLIAAghQAAgVgHgrIgOhMQgCgPACgFQACgFAFgCQAFgDAEADQADACADAGQAGAOAGAlIAIBAIAEATQABAJAAAaQgBAVADANQAQgGAWAAQAygBAbATIANALIAHAGIAFAMIABAKQABAFACAEQACAEAEADIABAAIAAASIgEAWIgEAQQgBAGgGAKIgCACIAAAFQgBAFgHAJQgtA/gyBSQgfA0g4BjIgnBEQgJAOgGAEQgGAEgNAAIgFAAgAkOFgQgMAMgEAGQgEAHgCAJQgPAygaBmQgZBageA4QAOADAPABQALABAGgCQAHgDAHgNIBmi3QAfg0A6hSQgUAGgYgCQgbgDgZgNQgMgGgHgHQgIAMgKALgAi9DDIgTAGQgKADgGAFQgGAEgIAMIgHAMQgDAHAAAQQAAATADAJQAFANAPAKQALAIASAEIAUAEQAWACASgHIAQgIQANgJAKgPQgEgFABgJIADgOQAGgXgIgOQgDgFgKgIQgPgLgLgDQgMgDgUAAIgTAAgAnKibIg5gfQgQgPgKgFIgOgIQgJgHABgHQAAgEAFgHIAXgiQAUgeARgOQAFgFAFgBQAFgCAIAAIAIABIABAAIAAgBIAQABIAHgYQAGgVAEgKIAGgLIAKgeQACgFgBgDIgDgHQgCgGACgFIACgIIgCgFQgCgEACgIQAEgNAEgFQAFgIAJgDQAFgBAHACIAAgBIAGAEIAGADIADACQADAEADAMIACANIgEAQIgGAPQgGAMgTADQgIAcgHANIgGAMIgQArIAQACQAKACAEAEQADAEgBAKQgDAoAFAVQADALgBAEIgKAKQgDAEgFAIQgFAJgDAEIgIAIQgGAFgBAEIgDALQgDAGgEABIgBAAQgDAAgFgDgAndkwQgDAAgDADQgOANgLAPIgFAJIgWAdQAAAAgBABQAAAAAAABQgBAAAAABQAAAAAAABIADADQAMAIAGAGIAYAUQAQAMAUAHIAhgwIACgFQABgCgBgGQgFgTADgrIgugFIgIgBIAAAAgAmLncIgCAEIgCAJIACAGIABADIACACIACADIABAEQADgBABgEQADgHAAgKQABgDgCgCQgBgDgFgCIgCAAgACkjJQgCgDgDgJIgKgnQgKgjABgWIAAgHIACgEQACgJAKgIIABgBIgBgBIgVgTQgOgNgGgHIgHgJIgTgTQgDgEgDAAIgHAAQgGgBgDgCQgEgFgCAAIgFABQgDgBgHgFIgKgMIAAgBQgEgHABgIIAVgUIAHgCIAIAAIALAEIALAJIAKAKQAFAKgFASQATARAHAKIAHAKIAdAeIADADIADAEIAZgXQAHgGAFAAQAFABAIAHQAcAcATAJIAIAEIAEAFIABAEIABAKQAAAFAEAJQADAKABAFIABALQAAAIADADIAGAJQADAGgCAFQgCACgGADIg9AWQgWADgKADIgQAHIgGAAQgGAAgEgDgACplCQgGAFAAABIgBAGQABAUAEARIADAKQAFAUADAPQAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQABgBABAAQAOgEAIgBIAegFQAUgEATgKIgQg5IgCgFQgBgCgFgCQgRgIgfgggAA8m1IAGAAIACAAIADAAIADgBIAFAAQAAgCgDgDIgDgDIgJgGIgFgBQgDABgEADIgBABIABAEIACADIAAgBQAEAEACABgAjkj4QgSgDgIgGQgHgGgHgUIgQg0QgNgsgGgZIgIgpQgHgXAIgJQADgDAEAAQADAAAEAEQAHAIAEAUQALA3AjBqQABAFADAEQADACAIACQBeATBagIQAXgCAGgLQABgDABgLIABgVIABgIIADg1IgEgQQgBgEAAgNIAGiIIAAgaQAAgggEgRQgKgrgcgVQgIgGgCgDQgCgDAAgEQAAgDADgCQAFgEAHADQAYAJAPAVQAGAKAHARQAIAVACALQABAKAAAWIAAAOIgCBlIAAAGIACAnIAAAVIAAAEIAAAjQAAAegEAYQgBAJgEANQgCAHgCADIgCACIgDAGQgKAUgnAFQgdAEgiAAQg1AAhCgKgAjwnZQgXAAgOgKQgKgHgJgPQgKgQgCgQIAAgJQggAegeAXIgIgDIgGgEQABgEAFgCQApghAhghQAEgEAEgCIAAgDQACgHAHgKIALgOQAOgNAggEQAdgFAQAHQAJAEAJAHQAQAPAHASQADAIABAIQABAMgDAOQgFAVgQAQIgJAJIACADIgBAAIgFADIgFABIgHAFIgLABIAAACQgSAHgSAAIgFAAgAj1pcQgLADgDACQgFADgJAJIgMAPIABAFIAAAAQABAFgBALQgCAUASAUIAHAGQAEADAGABQALACAJAAQAQAAAPgHQAVgLAJgVQAGgPgDgOQgCgHgDgHIgHgKQgGgHgEgCQgLgIgQAAQgKAAgTAEgAkypWIgEgEIgCAAQgDgDAAgEQAAgGAEgIQAMgWAlgdIAQgLQALgHANgFIAngPIAQgEIACAAIAAgBIAEgOQABgHgBgEIgCgKQgBgGABgEQACgFAFgCQAGgBAEACQAEADADAIQABgFAHABIAJAFQAQAPAQAEQAJACATgBQAVgCAJgIQAHgIACgMQANgxgcg6QgEgJAAgFQAAgEADgDQACgDAEAAQADAAAFADQAFAGAEAHQAaAygHA3QgDAjgTAQQgPALgaADQgSABgOgCQgSgFgLgLIgPgVIgBgBQAFATgIARQgEAIgEADQgHAEgFgDIgHADIg2AcQgUALgYAUIgMAMQgHAHgDAHIgIAMIAAAAIAEAEIgBAAQgBAAAAgBQgBAAgBAAQAAAAgBgBQAAAAAAAAQgEACgEAAIgCAAgAhmqYQgWgCgNgVQgEgJAFgDQAEgDAHAGQAMAKAHACQAMAEAKgEQAHgDABgEIAEgIQAFgFAFAGQADAEgCAHQgCAGgGAGQgMALgRAAIgEAAgAimsBIgFABQgHABgFgBIgMgDQgPgEgFgKQgEgIABgKQACgUAMgJQgEABgFgDQgDgCgCgDIgMgQIgLgTIgEgJIgCgJQAAgKACgKQACgLAEgEQADgEAFgBQAEAAAEACQAFACABAIIgBANIAAAHIABAHIACAGQAIAQAHAIQAFAHABADQAFAJgHAHIgBABQAFgCAGAAQAKABAGAGQAEAEAAAHQgBAIgIACQgIAEAAACQAIABAFAEIAEADQAFAAADACQAEACABAEQACAFgCAEQgBAEgGAEIAAAAIgDAHIgBACQgCgEAAgDgAhOs4QgGgDgBgHQAAgHAGgDIAEgBIABAAQAIAAACAHQADAGgFAFQgEADgEAAIgEAAgAhrtyQgJgBgFgDIgGgDIgHAAQgEAAgCgDQgCgCABgDQABgHAHgCQAFgDAHADIAMAFQAIADARgDQALgCAFgEQAEgDADgGQADgEAAgGQgBgGgFgGQgIgJgQgKQgIgGgGgCIgPgFQgJgEABgIQACgIALgCQAPgCATAJQARAHAKAJQAHAHAJANIAEAJIABALQgBAKgDAGIgDAFIADABIgJAIQgEAEgKAFIAAgBQgSAKgUAAIgMgBgAjHuOIgIgHQgIgGgCgEQgCgDAAgEQABgEACgCQAEgEAHACIAJAFIAKAHQADACADAFQADAFgBAFQAAAEgDACQgDACgDAAQgFAAgHgFgAikubIgHgGQgEgDgIgEIgMgFQgGgDgBgFQgBgGAKgEQAEgBAJABQAJACAGADQAHADADAEQAEAFAAAHQAAAFgDAEQgDADgEAAIgDAAgAh9uvIgFgGQgDgFgIgFQgGgEgLgEQgIgCAAgEQABgEAHgBQAHgBAGAAQAJACALAIQAHAEAEAGQAFAIgEAGQgBAEgDAAIgCAAQgCAAgEgCg");
	this.shape_8.setTransform(256.3943,90.5368);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0000CC").s().p("AEKPLIipgKQgfgCgKgOQgEgHAAgPIgIhcQgBgTAFgHQAJgRAjgBIBogCQAUAAAKACQAMADARALIAtAiQAMAHAGABQAEABAQgCQAkgEAgAQQAVALANASQAOAUABAVQAAAXgOAMQgKAJgYADQgcADgmAAQgiAAgpgDgAC/MtIh7AFQAJAvACAyQAAAHADADQACADAIAAQA7AGAvABIBLAGQBEAGBFgIQAIgBADgEQAEgEgBgFQAAgMgHgLQgPgWgfgHQgXgGghAFQgMABgFgDIgJgJQgEgFgLgHIgsgcQgJgFgEgBQgHgCgNAAIgGAAgAkONuQgMgEgOgUQgfgugjhQIhFiaQgMgdAIgPQAEgGAOgJIBNgvQARgLAJABQASABARAeIAyBbQAKASACALQADAMgBATIgJA4IAAAUIAKAQQAVAfABAjQgBAYgKAVQgLAVgTALQgMAGgLAAQgHAAgHgDgAmOIZQgHADgBAEQgBADADAHQAXA3AUApIAeBHQAaA/AmA5QAGAHAEABQAGACAEgDQAKgFAGgNQANgXgHgeQgGgYgTgaQgIgLABgGIAEgMQACgFADgOIADg0IgBgOQgBgIgJgQIg8hrQgnAegrAZgAC6LxQgegKghABIgSABQgKAAgGgCQgEgBgCgBQgEACgGgDQgJgEACgMIAJgSIANgeIASgzQAQgsAFgXQAFgRAMgzQAJgqAJgYIABgCIgDAAIAEgHQAHgKAGgHIACAAIARgLQAUgLATgOIgBgEIAGAAQgCgIAAgJQgCgSAGgQIAIgPIgBAAIAAgBIABgDIABgBIgBAAQAAgFgCgCIgBgCIgBAAIgDgBIgBAAIgNgOQgDgCgHgLQgLgOgEgHQgHgTgFgIIgIgOIAAAEIgJgPIgJgCIgBgDIgBgEQgEgDgEgIQgag9ghhSIgLgcQgIgPgKgRQgMgSgDgJQgEgLABgSQACgxAKgZQABgFAEgDQAEgEAEACQAFABABAKQABAJgDArQgCAfAIATIASAfQAIANALAdIApBuIABAAQAIAOAKAYIAEAMIAIAKIgBABIAIAKQALAPAFAKIAHANIARAbIAIANIAKAIIAAgBIAAAAIAEAEIACAEIAIgIQAVgQAmADQAPAAAIADIAJAEIACACIABABIABAAIgBgHIAAgCQgJgagHghIgFgDIgGgEIADADIAHADIgHghIgVh1IgGgkQgBgJAAgaQABgWgCgOQgHgYgBgMQgFgXAHgPQADgKAHABQAEAAADAKIALAuQAHAnABAZQgBAaABADQAAAHAHAcIAmDRQADAQgEAKQAAADACACIgBABQAPAOAHAMQALATgFAiQgCAXgIAMQgDAGgJAGIAAABIABAEQgMAEgKAHIgHgBIgTAIIgDABIgDABQgRAegUAuQgjBMgPAmQgPAngaBPQgFAOgHADIgFABQgEAAgHgDgADMGYQgJAFgEAEQgDAEgCAIQgPAogHAqIgKA1QgFAUgOAnIglBhQgCADAAADQAzACAuAQQAih9BDiUIAUgrIgHgBIgEAAQgTgFgLgLIgEgCIgBgBQgDgIAAgIQgGgBgEgGIgHAAIgDgEQgTAPgWAMgAE3EWIgVAFQgIADgEAGQgEADgHALIgFAIIgDAJQgDAZAFANQADAHAHAKIACAEIALABIAOAGQAEABAIABIAOABIAOABIAQgEQAVgIAGgLQAEgIABgQIABgIIgBgGQgBgJgDgGQgDgHgSgPIgPgLIgSgEIgPgCIgCAAgAnOIJIAAAAIAAABgAjAH/QgJAAgOgKQgSgMgXgTQgJgHAAgHIAAgBQgBgIALgIIABAAQAMgKAWgPQAIgEAHgFIABgBQAggUAQgNIAqglIBphgQAUgRAMgEIAZgEQAQgGALAAIAAgFQABgMACgFQABgFAMgSQAJgQAHgFQADgFAIgFIASAZIgCABQgIAFgIANQgKAQgCAJQgDAOAHARQAFANANAMQAEAGAJAIQATAOATAEIASACQAKABALgDIAJAQIgCADQgTAMgTANIgHACIgBABIgHADQg3AXg/AdQg2AahkA1IhGAkQgOAGgHAAIgBAAgAAzDwQgTADgFAEQgIADgHAGQgoAihLBHQhHA9g4AgQAKAJAMAKQAJAGAGACQAIABANgGIC5hiQA2gbBdgkQgUgGgSgPQgVgRgPgZQgHgMgBgJQgOAGgNADgAn1FKIAEgHIgEAIgACtgTQgTgEgUgHIgNgGQgGgEgFgKQgFgHAAgGQgBgGADgKQAPgrALgXQADgGAFgEQABgBAHAAIANABIg2hGIgXgEQgTgDgIgGQgHgGgGgUIgEgMQgGgGgDgHQgFgLABgSQgNgrgFgYIgCgIIgHghQgFgXAHgJQADgDAEAAQADAAAEAEQAGAIAEAUQADAQAGAUIAOA1IAEABIAShZIAEgaIgEAAQgWAAgOgKQgKgHgJgPIgCgCIAAgBIAAAAIgEgIIgCACIAAAAQgEgWABgWQACgFACgEIACgDIADgFIACgGQABgHAHgKIAMgOQAOgNAggEQAdgFAQAHQAJAEAJAHQAQAPAGASQADAIABAIQACAMgEAOQgFAVgPAQIgKAJIgRAMIgFABQgBAAgBAAQgBAAAAAAQgBAAAAABQAAAAAAABIgCABIgBgBIAAABIgOAEIgDANQgFAagFA0QgCAPADAIQgBAIACAEIgCAFQAAAFgCAFIADACQAHAJAAAJQABAHgDAIIgBADIACABIAYAaQBQANBOgHQAXgCAFgLQACgDABgLIABgVQAAgHACgEQADgEAEAAIACAAIABAAQAEACABAIQACALgBAOQgBAQgGAIQgLAUgnAFQg2AIhLgHIALAOIAfApIALAOIgBAAQAJACAIAAIAAABIAAACIADgBIAAAEIAJgBQALACgBAIIgCAJQgCAEABAFIACAIIACAMQAAAKACAEIAEAKQACAFgEAGQgGAQgQASQgGAHgFACQgFADgIAAQgGAAgIgCgACeiJQAAAAgBAAQAAABAAAAQgBAAAAABQAAAAgBABQgHAOgIAUIgMAdQgCAGABACIAAAHIAGAHQACADAEABIAXAIQANAFAJABQAEAAAEgBQADgBAEgFIAWgcIACgGQACgDgCgFIgGgPQgDgHgGgWIgFgBIgGABQgFAAgCgCIgBgCIgIgDIgEgEIgGAAIgJgBIgCgBIgCAAgAC4iWIABAAIAAgBIgBABgABMkGIABADIAGADIgEgIIgDACgABFkYQADgBACgGIACgDQACgGAAgEIgFgDIgDAAQgEABgEgCIAHAYgABYngQANgBAMgGQAVgLAIgVQAGgPgDgOQgBgHgEgHIgGgKQgGgHgEgCQgMgIgQAAQgJAAgTAEQgMADgDACQgFADgIAJIgMAPIABAFIAAAAQABAFgCALQgBAUARAUIAHAGQAEADAHABIARACIACgTgAHVg/IhAgKQgUgJgLgCIgRgCQgKgDgCgIQgBgDACgJIALgnQAJgkALgSIAEgGIAEgEQAGgGAMgCIACAAIgBgBIgIgcQgGgSgBgJIgCgLIgHgbQgBgEgCgCQgBgBgGgCQgEgEgCgDIgCgHIgFgDQgCgCgDgHQgDgLAAgFIAAAAQAAgJAFgHIAcgGIAIACIAGAEIAIAJIAFANIADAOQAAALgNANQAHAYACANIAAAMIAKAoIACAFIAAAEIAhgHQAJgCAFADQAFADACAJQAKAnANASQABAEADADIABAGIgBAFIgEAIIgEAOIgEAPIgEAKQgEAHABAFIAAALQAAAGgEADIgFABIgEgBgAGZjHQgIABAAABQgCABgCAEQgJARgFARIgCAKQgGAUgGAPQAAABAAAAQgBAAAAABQAAAAAAABQAAAAABABQAAAAABABQAAAAAAAAQABAAABABQAAAAABAAQAOADAHAEIAdALQATAGAWAAIAQg9QAAgDgEgFQgKgQgMgqgAFxlsIAAADIABABIACAGIAFADIADACIACAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABIAEABQAAAAAAAAQAAgBAAgBQAAAAAAgBQAAgBAAgBIgBgEIgFgJIgEgEQgDgBgEACIgCAAgAgHhnIABgDIgBADIgBAFIgBABIACgGgAE2lVIgBgKIgFgSQgBgEAAgNIAHiIIAAgaQgBgggEgRQgJgrgcgVQgIgGgCgDQgCgDAAgEQAAgDACgCQAFgEAIADQAYAJAPAVQAHAKAGARQAIAVACALQACAKAAAWIAAAOIgCBlIgBAGIACAnIABAJQAAALgCAIIgGAYIgCAKQgCAGgFAAQgFAAgDgHgAAJonIABgBIgBACIAAgBgAAFpDQgGgDAAgIQgBgGAEgIQAMgWAlgdIAQgLQAKgHANgFIAogPIAPgEIACAAIAAgBIAFgOQABgHgBgEIgDgKQgBgGACgEQACgFAFgCQAFgBAEACQAFADADAIQABgFAGABIAJAFQARAPAQAEQAJACASgBQAWgCAIgIQAHgIADgMQANgxgcg6QgEgJAAgFQAAgEACgDQADgDADAAQAEAAAEADQAFAGAEAHQAcAygHA3QgEAjgUAQQgOALgaADQgTABgOgCQgSgFgKgLIgPgVIgBgBQAEATgIARQgDAIgFADQgGAEgGgDIgGADIg3AcQgTALgZAUIgMAMQgGAHgEAHIgHAMQgFAEgFAAIgDAAgADTqFQgXgCgMgVQgFgJAFgDQAEgDAHAGQAMAKAHACQAMAEALgEQAGgDACgEIADgIQAFgFAFAGQAEAEgCAHQgCAGgGAGQgNALgQAAIgEAAgACTruIgFABQgHABgGgBIgMgDQgOgEgGgKQgDgIABgKQACgUAMgJQgFABgEgDQgDgCgDgDIgMgQIgLgTIgEgJIgBgJQgBgKACgKQACgLAFgEQADgEAEgBQAFAAADACQAFACABAIIAAANIgBAHIABAHIADAGQAHAQAHAIQAGAHABADQAEAJgHAHIAAABQAFgCAGAAQAJABAGAGQAEAEAAAHQgBAIgHACQgIAEgBACQAIABAGAEIAEADQAFAAACACQAEACACAEQABAFgBAEQgCAEgGAEIAAAAIgDAHIAAACQgCgEAAgDgADqslQgGgDgBgHQAAgHAGgDIAFgBIABAAQAHAAADAHQACAGgFAFQgDAEgEAAIgFgBgADNtfQgIgBgFgDIgHgDIgHAAQgEAAgCgDQgCgCABgDQACgHAGgCQAGgDAGADIAMAFQAIADASgDQALgCAEgEQAFgDACgGQADgEAAgGQAAgGgGgGQgHgJgQgKQgIgGgHgCIgPgFQgJgEACgIQABgIALgCQAPgCATAJQASAHAJAJQAIAHAIANIAFAJIAAALQgBAKgDAGIgCAFIACABIgIAIQgFAEgKAFIAAgBQgRAKgUAAIgNgBgAByt7IgJgHQgIgGgCgEQgCgDABgEQAAgEADgCQAEgEAGACIAKAFIAKAHQADACACAFQAEAFgBAFQgBAEgCACQgDACgEAAQgEAAgHgFgACVuIIgIgGQgEgDgHgEIgNgFQgGgDAAgFQgCgGAKgEQAFgBAJABQAIACAGADQAHADADAEQAFAFAAAHQAAAFgEAEQgDADgDAAIgDAAgAC8ucIgFgGQgEgFgIgFQgGgEgLgEQgHgCAAgEQAAgEAHgBQAIgBAGAAQAJACALAIQAGAEAFAGQAEAIgDAGQgCAEgDAAIgBAAQgDAAgDgCg");
	this.shape_9.setTransform(271.8813,88.9758);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0000CC").s().p("ACePXIgqgBIhsgHQgfgCgJgOQgEgHgBgPIgHhcQgCgTAFgHQAJgRAjgBIBngCQAUAAALACQAMADAQALIAuAiQALAHAGABQAFABAPgCQAkgEAgAQQAVALAOASQAOAUAAAVQAAALgCAIIgEACQgbAKgbAGQgqAIhDAAIgmAAgABlM7Ih6AFQAJAvACAyQABAHADADIABABQAAAEADACQACACAHAAIANAAIAGAAIAGAAICiAEQAoABAXgCQAXgBATgEIACAAQANAAAHgEIAKgHIADgCQgBgJgFgIQgQgWgfgHQgXgGggAFQgNABgFgDIgJgJQgDgFgLgHIgtgcQgIgFgFgBQgGgCgOAAIgGAAgAgdMUQgHgEgBgPQgBgTACgoQABgogBgUQgBgSgFglIgSiNQgCgXACgMIACAAIABgFIARg+IAMgWIADgCIgBAAIgBgBIgGgFIgGgFIgBAAIAAgBIgIgRQgBgEAAgVIAAgIIABgQIABgHIAEgLIAAAAIACgEQALgUAOgMIgBAAIhNkZQgFgPAAgKQAAgKAGgQQAJgcAQglIAEgHIABgCIAAAAIABgDIAAAAIACgCIABgBIAEgDIADgBIAEAAIACAAIADACIAAAAIABABIAAAAQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAABIAAAAIABAEIAAAEIAAABIgBABIAAACIgBAAIgBADIAAAAIgBACIgDAFIAAADIgCACQgQAfgDAhIgBAEIgDARIAAgCIgBAMIAAACIABALIABAGQABAIAKAYQALAcAKAyQALA6AHAWIALAgQAFATgBAOIgCAIIAKgHQASgJAfgBQAaAAAVAFIARAIIAHACIABACIAKAMIAHAEIABAAIABgJIAAgOIAAgCIAAgDIAAgFIAAgCIAAgBIABgCIgQhaIgGglQgEgagBggIgGhrQAAgQACgGQADgGAIgGIAOgJIALgJQAHgEAFACQAFABACAFQACAFgBAFQgCAIgKAIIgMALQgDAFABAKIACBKIADA9IAEAjIADAYQAAAvAKAyIACAMIACASIgFAfIAAADIAAACIgBAAQADAMgCAPIgDAXIgEAQIgBADIgDACIgHAIIgGALIgIAIQgGAHgDARQgBAIABAEIgGAcIAAAAQgJAqgHAvQgKA7gQBxIgLBPQgDAQgEAFQgFAHgQAFQgUAIgcAJIgJABQgFAAgDgCgAgFFcQgCAFgFAJQgEAJgFAVIgCAFQgCAKgFAJIABAAIgDANQgBAHABAKQAFA0ANBoQAKBcgHA/QANgCAPgEQAKgDAEgEQAGgGACgPIAbjPQAFgkAMgyQABgVAGgVIAJgeIgRACQgaAGgagGQgUgFgOgKIgBADgAA2DFQgXACgLADQgTAGgJALIgIALQgIAJgBAFQgDAHAEAGIgBALQABAUAIAIIABABQAFAOAOAKQALAHASAFIANADIA5gKIAGgDQANgJAJgOQgEgFABgJIAEgPQAFgWgHgOQgEgGgKgIQgJgHgIgDIgCAAIgGgHQgKgHgWAAIgFAAgAl/KQQgJgKgDgYQgGg3AGhWIAKipQACgfAOgKQAHgEAPAAIBcgIQATgBAHAFQARAJABAjIACBoQAAAUgCAKQgDAMgLARIgiAtQgHAMgBAGQgBAEACAQQAEAkgQAgQgLAVgSANQgUAOgVABIgCAAQgWAAgLgOgAlTEmQgHAAgDADQgDACAAAIQgGA7gBAvIgGBLQgGBEAIBFQABAIAEADQAEAEAFgBQAMAAALgHQAWgPAHgfQAGgXgFghQgBgMADgFIAJgJQAFgEAHgLIAcgsQAFgJABgEQACgIAAgSIgFh7QgvAJgyACgAiZGNQgFgDgDgMQgIgfgRgcIgKgOQgFgKgCgGIgBgFQgFgDAAgGQgBgKALgEQAEgCAPgBQALgBAWgEIA0gMIAJgCQAFABACABIACAEQAGAKgHAKIhmAUIgFABQAZAtAKAwQAngMArgKIABABIABACQABAGgDAHIgDAEIAAACIg/APIgKABQgGAAgDgCgAEFF5IgEAAQgTgDgNgKIgEgBIgBgBIgBgCQgDgGgBgHQgGgCgFgEQgPAAgRACIgNABIgCgBIAAgCIACgJQACgHAGgEIAFgEIAOgBQgDgIgBgJQgEgSAFgRIAEgMIADgHIACgFIABgEIADAAIAGgKIABgCQAGgHAJgEIAEgBIAAAAIACgBIAEgDQAPgGAWgBQAPgBAJACIANAGIgCgIIgBgBQgLgagMggIAAAAIAAAAIgLghIgkhxIgJgiIgFgjQgDgXgDgMIgNglQgHgWAEgQQACgKAIAAQAEABAFAJIAQAsQAMAmADAZIAEAeIALAjIA+DJQAGAQgCAKIABAGIAAABQARALAIALIAFAIQAIASAAAbQAAAXgGAMQgEAHgGAHIAAABIAAADIgQAKIgFAEIgGAAIgSAKIgDAAQgIADgLAAIgTAAgAD3DlIgUAHQgHAEgEAFIgEAHIgFAIIgEAJIgBAJQgBAZAGANQAEAHAHAIIAEAEIALABIAOAEIANABIAOAAIAOgCQAHgBAIgEQATgKAFgLQAEgJgBgQIAAgIIgCgGQgCgJgDgGIgHgHIgRgMQgNgIgDgBQgGgCgNgBIgJAAIgIABgAEshFQgJgCgGgDQgFgEgGgKQgbgqgMgbQgEgHABgFQAAgCAGgHQAQgPATgKQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIgMgHIhgg6IgVgLIgJgIIgFAGQgHACgJAAQgXgBgMgNQgJgIgDgSQgBgMAEgIIgDgCIgFgGIgPgdIgGgKIgGgIIgDgIIgFgIIgDgIQgDgKgKgPIgOgWQgQAFgRgBQgXAAgOgKQgKgHgJgPIgGgLIgBACIgHgiIgCgCIAGgIQABgFADgEIACgDIADgFIABgGQACgHAHgKIALgOQAOgNAggEQAcgFAQAHQAJAEAJAHQAQAPAHASQADAIABAIQABAMgDAOQgFAVgQAQIgJAJIgOAKIACAEQAIALAQAcIAlBEQAEAIAAAFIAFAAIAAgEIAlAGIgBAKIAEABQAKAEACAKQADAGgCAIQAAABAAAAQAAABAAAAQAAABAAAAQAAABABABQAAgBAAAAQAAAAAAAAQABAAAAAAQABAAAAABQAZAKAiAUIACABIAQAKIAqAcQAVALAMAJIAGgJQAKgIAHAHIAGAIQACAFAGACIAIAEIAMAIQAIAGAGABIAMAFQAFACADAHQAJAQADAaQACALgBAFQgDALgSALQgTANgXAMIgPAEQgDABgFAAQgGAAgHgBgAEdi4IgHAAQgCABgEAEIgHAGIgEACQAAABAAAAQAAABAAAAQAAABAAABQAAAAABABQAGAQAMAUIARAfIAFAHIAIAEQAHACADgBQADAAAEgDIAagMQAPgFAHgJIAHgGQABgDgCgHIgHgmIgFgHQAAgDgGgCQAAgBgSgEQgJgDgXgLIgGADQAAADgDACQgEAEgFABIgBAAIgJAEgABkk0QACACAIADQAFADADgBQAEgCAAgHIABgDQABgIgBgCIgGgCIgEACQgFAEgIgCIgHgDQACALAFAFgAgrpSQgLADgDACQgFADgJAJIgMAPIABAFIAAAAQABAFgBALQgCAUASAUIAHAGQAEADAGABQALACAJAAQAQAAAOgHQAVgLAJgVQAGgPgDgOQgCgHgDgHIgHgKQgGgHgEgCQgLgIgPAAQgKAAgTAEgAgajuQgSgDgIgGQgHgGgHgUIgQg0QgNgsgGgZIgIgpQgHgXAIgJQADgDAEAAQADAAAEAEQAHAIAEAUQALA3AjBqQABAFADAEQADACAIACQBXASBVgGQACACAHACQAJAEgDAHQgBADgEACIgFAAQgdAEgiAAQg1AAhBgKgADBkfIAAgPQAAggACgfIAAgDIgCgKQgBgEAAgNIAGiIIAAgaQAAgggEgRQgKgrgcgVQgIgGgCgDQgCgDAAgEQAAgDADgCQAFgEAHADQAYAJAPAVQAHAKAHARQAIAVACALQABAKAAAWIAAAOIgCBlIAAAGIACAnQABARgDALIgFAYIgCAKIgBACIACArIgBALIgCAFIAAAFIgGABIgBAAQgFAAgHgFgAhmowIABgBIgBACIAAgBgAhppMQgIgDAAgIQAAgGAEgIQAMgWAlgdIAQgLQALgHANgFIAmgPIAQgEIACAAIAAgBIAEgOQABgHgBgEIgCgKQgBgGABgEQACgFAFgCQAGgBAEACQAEADADAIQABgFAHABIAJAFQAQAPAQAEQAJACATgBQAVgCAJgIQAHgIACgMQANgxgcg6QgEgJAAgFQAAgEADgDQACgDAEAAQADAAAFADQAFAGAEAHQAbAygHA3QgDAjgUAQQgPALgaADQgSABgOgCQgSgFgLgLIgPgVIgBgBQAFATgIARQgEAIgEADQgHAEgFgDIgHADIg1AcQgUALgYAUIgMAMQgHAHgDAHIgIAMQgEAEgFAAIgDAAgABjqOQgWgCgNgVQgEgJAFgDQAEgDAHAGQAMAKAHACQAMAEAKgEQAHgDABgEIAEgIQAFgFAFAGQADAEgCAHQgCAGgGAGQgMALgRAAIgEAAgAAjr3IgFABQgHABgFgBIgMgDQgOgEgFgKQgEgIABgKQACgUAMgJQgEABgFgDQgDgCgCgDIgMgQIgLgTIgEgJIgCgJQAAgKACgKQACgLAEgEQADgEAFgBQAEAAAEACQAFACABAIIgBANIAAAHIABAHIACAGQAIAQAGAIQAFAHABADQAFAJgHAHIgBABQAFgCAGAAQAKABAGAGQAEAEAAAHQgBAIgIACQgIAEAAACQAIABAFAEIAEADQAFAAADACQAEACABAEQACAFgCAEQgBAEgGAEIAAAAIgDAHIgBACQgCgEAAgDgAB7suQgGgDgBgHQAAgHAGgDIAEgBIABAAQAIAAACAHQADAGgFAFQgEADgEAAIgEAAgABetoQgJgBgFgDIgGgDIgHAAQgEAAgCgDQgCgCABgDQABgHAHgCQAFgDAHADIAMAFQAIADARgDQALgCAFgEQAEgDADgGQADgEAAgGQgBgGgFgGQgIgJgQgKQgIgGgGgCIgPgFQgJgEABgIQACgIALgCQAPgCATAJQARAHAKAJQAHAHAJANIAEAJIABALQgBAKgDAGIgDAFIADABIgJAIQgEAEgKAFIAAgBQgSAKgUAAIgMgBgAACuEIgHgHQgIgGgCgEQgCgDAAgEQABgEACgCQAEgEAHACIAIAFIAKAHQADACADAFQADAFgBAFQAAAEgDACQgDACgDAAQgFAAgHgFgAAluRIgHgGQgEgDgIgEIgMgFQgGgDAAgFQgBgGAJgEQAEgBAJABQAJACAGADQAHADADAEQAEAFAAAHQAAAFgDAEQgDADgEAAIgDAAgABMulIgFgGQgDgFgIgFQgGgEgLgEQgIgCAAgEQABgEAHgBQAHgBAGAAQAJACALAIQAHAEAEAGQAFAIgEAGQgBAEgDAAIgCAAQgCAAgEgCg");
	this.shape_10.setTransform(281.0381,88.739);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_2,p:{x:73.231,y:94.9758}}]},2).to({state:[{t:this.instance}]},2).to({state:[{t:this.shape_3}]},2).to({state:[{t:this.shape_4}]},2).to({state:[{t:this.shape_5}]},2).to({state:[{t:this.instance_1,p:{x:128.9,y:-7.9}}]},2).to({state:[{t:this.shape_6}]},2).to({state:[{t:this.shape_7}]},2).to({state:[{t:this.shape_2,p:{x:212.081,y:92.3258}}]},2).to({state:[{t:this.instance_2}]},2).to({state:[{t:this.shape_8}]},2).to({state:[{t:this.shape_9}]},2).to({state:[{t:this.shape_10}]},2).to({state:[{t:this.instance_1,p:{x:266.45,y:-13.15}}]},2).to({state:[]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-13.1,357.7,208.79999999999998);


(lib.boca = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000CC").s().p("Ai5A6QgxAAgXgMQgRgJgJgSQgIgTAHgPQAHgRAWgIQAPgGAYgBQBJgFCNgBQCPgCBFgEQAagBAJACQATAEANAQQAMAQgBATQgBARgNAPQgNAPgSAHQgQAGgVACIgmABg");
	this.shape.setTransform(28.8206,6.0583);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0000CC").s().p("AiNB7QgSgBgPgFQgVgGghgYQgbgTgHgNQgGgNABghIAEhEQAAgMADgHQAHgRAegHQARgEAkgDQC/gPDCACQAYABAJAGQAIAHAGAQQAIAYgCAqQgBAegJANQgFAIgSAOIgkAZQgVAOgZAMQgfAOgZAHQgaAGg+ACIh0AEIgTAAIgPAAgAitgfQgFASAMARQAMARATAHQAQAGAWAAIAogBIAzAAQAeAAAUgCQA8gIAxggQAYgRAKgRQg1gCg0AAQiAAAh/AOg");
	this.shape_1.setTransform(29.9644,10.2511);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0000CC").s().p("AguDuQgxgDgxgIQgqgGgZgLQgegMgogfQgtgigSgeQgSgdgLgzQgQhEABgyQABg2AZgaQAQgQAcgHQATgFAggBIBogBQA9AAAqgGIBbgOQAigEBDgDIBbgFQA7gCAaAEQAZADAOALQARAOAJAgQAXBLgKBMQgFAkgLAbQgTAwgoAmQghAfg1AbQgZANgfAMQgfALgYAGQg5AOhFAAIgigBgAkpiHIADAoQAAAaACANQACAWALAqQAHAbAHANQAKAUAWARQAOAMAcAQQATAMAJACQAOAEAbAAQAJACAOAFIAXAHQAVAGAogBIA7gBQAhgCAZgGQAggHAjgQQAugVAcgXQATgPAMgRQAdgkAHgvQAIgvgQgsQgGgRgJgFIgEgCIAAACQACAngJAVQgGANgRAUQgOASgNAJQgPALgbAIQgyAPgmAEQgMABgrABIgtABQg5ABgdgCQgwgCglgJQgmgKghgTQgTgLgFgLQgDgGAAgOQAAgbADgcIABgFIgcABgAjNh7IAAAbQAzATAYAEQAaAFA3AAIAtAAQAxAAAagCQAqgCAggJQA5gPAJgjQABgGAAgSIhQADQg+AEgQACIhFAIQgyAFhbgCIgzgBIACANg");
	this.shape_2.setTransform(28.9758,13.3048);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0000CC").s().p("AkjCRQgcgHgRgHQgYgKgQgNQgRgOgVgcQgRgXgGgMQgOgcADggQACgfAOgeQAVgqAlgYQArgbBWgEQBXgECYAGQCqAHBEgBQBEgBAeAFQA4AMAbAkQAKAOAIAVQAEANAGAZQAGAXABAMQADATgDAPQgGAbgaAdQhLBRicAaQhLAMhQAAQiXAAiqgtgAlBhbQgaAKgRAVQgTAWAAAaQASAAAVARIAPAQQAKAKAHAEQAPALAeAIQA/ARBIAPQBEAPArACQAhABBGgGQBDgGAkgHQA4gLApgUQAigQAUgVQAQgRABgPQACgMgJgWQgIgRgHgGQgJgIgYgCIgYAAQABAggJAVQgMAdghAXQgeAYggAKQgTAGgZACQgPACgfAAQhQACgxgDQhWgEgwgfQgUgNgSgSQgYgYgGgUQgIgYAIghQgmACgVAIgAjAhUQAGANASANQAWAQAYAIQAUAGArACICSAHQAwACAWgJQANgGAMgJQANgIAEgJQAEgGAAgLIAAgJQhPgBh8gHIjGgJQACALAEAGg");
	this.shape_3.setTransform(30.7123,13.3487);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0000CC").s().p("ABnBqQgagEgqAAIhDgBQgVgBgLgFQgSgJgBgRQAAgJAGgIQAGgHAJgEQALgFAaAAIBvABQApAAARALQANAJAEAQQAEARgKAKQgJAJgPAAQgJAAgTgDgAAnAIQhdgCg2gGIhNgMQgugIgfgBIglgBQgVgBgOgHQgWgMACgQQACgLAMgIQAPgJAbgDQAwgFBIAJIB4APQAsAEBGgBQBBgBAogFQA4gGAtgQIAYgIQAOgEALgBQANgBAMAGQAMAHAEALQAEAKgDAMQgDALgIAIQgLALgbALQg5AVhJAGQgmAEg1AAIgsgBg");
	this.shape_4.setTransform(30.5058,6.6429);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0000CC").s().p("AgkCTQgPgBgKgEIgcgQQgUgKgJgHQgngcgDhFQAAgaAHgMIAHgOIABgQQAAgLAQgVQASgWALgJQAigbBFAAQAPgBANADIAcAKIAhAMQAUAJAQAQQAWAYAHAfQADAOABAbQAAAfgGARQgEAOgMARQgNASgMALQgjAjgtAFIgsAAIgaAAgAgTg4QgkABgRAYQADAIAAAPQAAARABAGQAFAVATAKQAJAFARACQAcADAVgIQAagLAIgYQAFgMgDgMQgDgNgKgIQgEgEgLgFQghgPgYAAIgBAAg");
	this.shape_5.setTransform(27.275,6.9875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0000CC").s().p("AgNCzQg3gCgigIQgbgGgrgRQglgOgXgNQgfgRgUgXQglgrgCg/QgCgeAIgeQAKgpAYgTQASgNAmgHQBRgOB+AEQC5AFAXAAQAdgBANACQAXADAQAKQAQALAPAaQARAeAEAdQAKBEg3BJQgXAfgZASQggAXgwALQg/ARhWAAIgNAAgADGgiQgXAPgtAIIgiAFQASAcAFA4IABAOIAGgBQAxgMAYgVQATgQAXgnIAKgTQAFgMgBgLQAAgJgFgMIgLgUIgBgDQgMAfgcASgAjyhqQgEAEgCAJQgGAaAAANQgBARAGAUQADALAKAXQAFAOAEAFQAHAIAPAJQAoAXAtANIgBgEQgIgbADgSQADgRATgZQgPgBgMgEIgVgIIgLgGQgggPgOgPQgMgNgEgRQgDgOACgMIgDgBIgEAAQgGAAgDACgAithpQAGAKAPALQAVAMAXAFQAPADAfABQBUACAmgEQAcgDAngIQAlgGAKgSQhOABiSgDIhYgCIgjgBg");
	this.shape_6.setTransform(24.865,10.1708);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[]},1).to({state:[{t:this.shape_5}]},2).to({state:[{t:this.shape_6}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-14.2,-10.5,89.9,47.7);


// stage content:
(lib.cicloandarbotonsonidoversionclasesincamara = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {Ah:114,M:115,Uh:117,S:119,"Ah":123,"M":126,Neutral:128,"M":131,"Neutral":133,"Uh":144,"S":149,"Ah":152,Ee:154,L:156,"Neutral":158,"Uh":179,"Neutral":184,"Ah":187,D:190,"Neutral":192,"Ah":195,"D":198,"Neutral":199};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,114,200];
	this.streamSoundSymbolsList[114] = [{id:"KurtRussellisfuckingcultDeathProof20072",startFrame:114,endFrame:200,loop:1,offset:1877}];
	// timeline functions:
	this.frame_0 = function() {
		this.clearAllSoundStreams();
		 
	}
	this.frame_114 = function() {
		var soundInstance = playSound("KurtRussellisfuckingcultDeathProof20072",0,1877);
		this.InsertIntoSoundStreamData(soundInstance,114,200,1,1877);
	}
	this.frame_200 = function() {
		var _this = this;
		/*
		Detenga la animación completa.
		*/
		createjs.Ticker.removeEventListener('tick', stage);
		
		
		var _this = this;
		/*
		Al hacer clic en la instancia del símbolo especificada, se ejecuta una función.
		*/
		_this.button_1.on('click', function(){
		/*
		Inicie la animación completa.
		*/
		createjs.Ticker.removeEventListener('tick', stage);
		createjs.Ticker.addEventListener('tick', stage);
		});
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(114).call(this.frame_114).wait(86).call(this.frame_200).wait(30));

	// muñeco_yendose
	this.instance = new lib.CachedBmp_1();
	this.instance.setTransform(-10.6,179.55,0.5,0.5);

	this.instance_1 = new lib.muñeco("synched",0);
	this.instance_1.setTransform(546.1,1185.9,10.1914,10.1914,0,0,0,51.9,98);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},201).to({state:[{t:this.instance_1}]},4).to({state:[{t:this.instance_1}]},24).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(205).to({_off:false},0).to({x:691.15,startPosition:9},24).wait(1));

	// boton_volver
	this.button_1 = new lib.Símbolo1();
	this.button_1.name = "button_1";
	this.button_1.setTransform(649.15,70.35,1,1,0,0,0,53.1,33.7);
	this.button_1._off = true;
	new cjs.ButtonHelper(this.button_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.button_1).wait(200).to({_off:false},0).to({_off:true},1).wait(29));

	// boca
	this.instance_2 = new lib.boca("single",0);
	this.instance_2.setTransform(382.4,380.25,1,1,0,0,0,28.8,6);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(98).to({_off:false},0).wait(16).to({startPosition:3},0).wait(1).to({startPosition:4},0).wait(2).to({startPosition:4},0).wait(2).to({startPosition:1},0).wait(4).to({startPosition:5},0).wait(3).to({startPosition:0},0).wait(2).to({startPosition:0},0).wait(3).to({startPosition:0},0).wait(2).to({startPosition:0},0).wait(11).to({startPosition:9},0).wait(5).to({startPosition:1},0).wait(3).to({startPosition:3},0).wait(2).to({startPosition:4},0).wait(2).to({startPosition:9},0).wait(2).to({startPosition:0},0).wait(21).to({startPosition:8},0).wait(5).to({startPosition:9},0).wait(3).to({startPosition:3},0).wait(3).to({startPosition:9},0).wait(2).to({startPosition:0},0).wait(3).to({startPosition:3},0).wait(3).to({startPosition:9},0).wait(1).to({startPosition:0},0).to({_off:true},1).wait(30));

	// cara
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0000CC").s().p("EAm7AhbQAFgFABgGQA9iuhfkTQgWhDgXgiQgWgnhEg4QhIhJgzgXQgogQhvgRQhlgRgtgiQgigWAAgcQgMgzBPgcQEUh2D8C0IBaBJQBJBJAKARQA0A4AmBaQBbDggBDVQAABUgLBJgEAaDAhbQALiXgLhlQgzlyl4jmQkNidnGg+QhmgMgigcQgcgWgMgiQgKgnAXgcQAVgWBKgMQHtgRFSCYQGvC/CjGCQBgDcgGEpIAAAngEghvAhbQgiitgGiNQAAhfAMhPQAFARARARQAGgoAhhIQA+ijBDhZQAuhEBOg+QBJg9B2g5IKnjxQDahJCHgFQAhAAAjAFIAAjbQAAgcAEgWQjfhriojPQhPhmgHg9QgEgsAWgtQAWgtAogRQBUgQA4BDQAnAiA4BTQBEBaCoBfQBlA4AyARQBVAWBwAAQEYAMCRhxQBahDAzhlIAngsQAWhaA4gGIAdgKQBDAWARAiQAQAWAAA3IAABlQgLBDgRAMIgFAFIgtBEQiNDEjJBDQAGAXAFAcQAGAhgBAdQABA3gGAzIAAB2QAAAtgLAcQgLAtg5A4QhkBUgzARQhCALgugFQhUAAhUgSIhOgWIhDgiQhPgygLgWIgXg4IgFgGIgGAAQgnAihxAyIppD3Qh1AoiSBZQhEAngnAoQgnAygnBlQhPC/gcBlQgMAngFAdQALBCARBJgAlsL9IAcBDIAnAzQAoAbAtAAQAnAMBIAAIA0gGIAmgWIAtgtIAGg+IgGiSQAAgiALghQg9AFg9gFQipAAiBgXgEgsFAhbIAAgFQBDi6CzhfQAjgWAsgLQALgGARAAIAsAAQAdgLAXgFQA9gMAtAWQAnAXARA4QAMAzgcAsIg4BJIgNAXQgKgGgLAAQg4gRhEAnQgnASgiAbgA1ChdQiSgygsgiQhrhUgMiNQgKiMBZhqQAog4BCgoQBKgcBqAAQBrAAAtAnQAhAXARAnQARAogWAhQgiA4iBAAQiBgLgcBDQgRAoAXAsQAWAoAnAQQA4AdB1ARQBxAhABBUQAFAogiAnQghAcg0ALIgSABQg6AAhhgdgALqi8QgFgLAAgGQgRALgLAAIg5gWIgQgWIAAgMQgigWAFgoQgFgnARgcQAng9BlgMICjgGQAngKAGgSQAQgWghgtQgtg4gngLQgcgGgzARQg5ARgbgGQgtAAgigtQgcgtALgtQARg4BEgnQBagyBqAFQBfAMBJAyQAMAFAFAGQC0B8gWDsQgMBIgcAtQgtBJhaAiIgyALIjbARIgtAAgABUo6Qg4hOAuhJQAhg+BDAAIALgGQA5AMAbAcQAoAnAFAtQAAAngLARQgQAzg5AcQgeANgaAAQg1AAglg1gApupKQgohKA/g9IAtgXIAcgFIAFgGQBDALAcA4IALA5QgLBUhOARQgOADgMAAQg4AAgkg7gAvJpKQgSgMgcgyQgQhVAAhZQAAhlAcguIAig3QAFgRAQhrQAXhaA9AGQAoAAAiBJQAnBlgsBfIguBmQgFAhAAA9QAABEgMAcQgLAzgcAWQgVAVgWAAQgOAAgPgJgAH5s2QgQg4AAiBQAKg+gWgtQg+g4gMgoQgFgcAWgcQAXgcAigFQA9gGA5AtQAnAiARAiQAcAygLBDIgGCjQgLBUgXAiQgWAhgXAGIgFABQglAAgkhEgAzosVQgXAAgcgcQgcgigQgQIhDg+QgcgoAAheIAFjnQAQgsAjgiQAxgyASgGQA4gSAsAiQAuAtgRAtQgGAngsBEIgMBUIAFBgQAHAQAnBEQAcA9gGAnQgTBAgpAAIgNgCgAM5vTQgdgRgKgcQgSgnABhVQgFhOg5ieQgWhIgdgcQg4g4AAgXQAAghAcgSQAoghA9AWQAtARAiAtIAyBJIAnBwQBEDQghCBQgXA4gdALQgIAFgLAAQgQAAgUgKgAkpxaQi4gXhhhJQg3giAAgyQgGgnAtgiQAzgWAnARIBgAsIBOAMQDhAWCFgcQBlgWA+gyIA9hVQAignARg4QALgiAAhPQgLhCgRgiIgthaQgnhgA+hIQAcgcAxgGQAuAAAhAcQAoAcAnBlIAiA9IAFBVQAAD2gxBxIhKBwQg4BDgnAXIg/AtIhOAnQgyAXhEAAQhPAHhNAAQhoAAhigNgAG70TQAGgdAXgWQgSAWgLAigAw648Qg9gzgegzQgbgtAAhwQgLhOAcg4QAihJBDAAQA+AAAbA9QAYAzAABDQAABUAEARIAoA4QAoA5gSAyQgLBJg9AAIgJABQgvAAgzgzgAjU5ZQgRgnAWhPQAihDgGgtQgGgcgbgcQgigsgGgMQgWgoAFgsQAMgoAcgcQAngbAiALIA3AsIA5BEIAoBJQAVBUgRBlQgLBOgQAdQgnA4gzARQgMACgLAAQgyAAgWgqgAqE43QgcgFgtguIg+g9QgcgcgXhKQgniMBKhqQAhg4AngGQBDgWAdAnQARARALAnIAABJQgMBUAAAMQAHAWAmBDQAoA+gRA+QgcBIgvAAQgMAAgOgFg");
	this.shape.setTransform(395.9,386.0679);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(98).to({_off:false},0).to({_off:true},103).wait(29));

	// muñeco_de_frentw
	this.instance_3 = new lib.CachedBmp_2();
	this.instance_3.setTransform(319.85,224.4,0.5,0.5);

	this.instance_4 = new lib.muñecodefrente("synched",0);
	this.instance_4.setTransform(355.9,323.4,1,1,0,0,0,32.9,99);

	this.instance_5 = new lib.CachedBmp_3();
	this.instance_5.setTransform(338.75,282.6,0.5,0.5);

	this.instance_6 = new lib.CachedBmp_4();
	this.instance_6.setTransform(345,286.3,0.5,0.5);

	this.instance_7 = new lib.CachedBmp_5();
	this.instance_7.setTransform(339.6,282.2,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_3}]},32).to({state:[{t:this.instance_4}]},4).to({state:[{t:this.instance_5}]},48).to({state:[{t:this.instance_6}]},3).to({state:[{t:this.instance_7}]},3).to({state:[]},8).wait(132));

	// muñeco_DE_lado
	this.instance_8 = new lib.muñeco("synched",0);
	this.instance_8.setTransform(-11.75,332.25,1,1,0,0,0,51.6,97.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:102.4,startPosition:30},31).to({_off:true},1).wait(198));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(336.7,336.7,2763.9,2007.3999999999999);
// library properties:
lib.properties = {
	id: '95507B7F5EBD5C46A26E392A56CC828B',
	width: 800,
	height: 600,
	fps: 24,
	color: "#FF9999",
	opacity: 1.00,
	manifest: [
		{src:"images/CachedBmp_8.png", id:"CachedBmp_8"},
		{src:"images/CachedBmp_9.png", id:"CachedBmp_9"},
		{src:"images/CachedBmp_6.png", id:"CachedBmp_6"},
		{src:"images/CachedBmp_1.png", id:"CachedBmp_1"},
		{src:"images/ciclo andar boton sonido version clase sin camara prueba 2_atlas_1.png", id:"ciclo andar boton sonido version clase sin camara prueba 2_atlas_1"},
		{src:"sounds/KurtRussellisfuckingcultDeathProof20072.mp3", id:"KurtRussellisfuckingcultDeathProof20072"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['95507B7F5EBD5C46A26E392A56CC828B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;